$STITLE Solution report generation
DISPLAY 'Optimal value of the objective function', Z.L;
 
SET TH1  Column headers for product and input soln rpt tables
 /PRODUCTION, USE, SHIP-IN, SHIP-OUT, SHIPMENTS, DEMAND, FIXED-DEM, SUPPLY, FIXED-SUP,
  IMPORT, EXPORT, PRICE, SUBSIDY, TRANSFER, TOTAL/;
 
SET TH2  Column headers for general soln rpt tables
 /LOWER, LEVEL, UPPER, MARGINAL/;

SET PRIMP(P)  Primary products
 /BREADGRAIN, COARSGRAIN, FEEDGRAIN, OILGRAIN, POTATOES, SUGARBEET, SILAGE, GRASSPASTR,
  MILK, SLGHBEEF, SLGHPORK, SLGHPLTRY, SLGHSHEEP, EGG, PLTRYMEAT,
  EGRAIN, ERAPE, ESUGARB, EPOTATOES, EMILK, EBEEF, EPORK, ESHEEPM, EEGG/;

SET PRIMPFA(P)  Primary products in Output-regions
 /MILK, SLGHBEEF, SLGHPORK, SLGHPLTRY, EGG, SLGHSHEEP, BREADGRAIN, COARSGRAIN, OILGRAIN, POTATOES,
  SUGARBEET, SILAGE, GRASSPASTR/;

SET BIDRAG(P)  Paid supports
 /GACRSUB, COMP4SUB, FORSUB, CATTLESUB, SOWHLTSUB, ECOSUB, ES1*ES6, NATSUB,
  COMPSUB, COMPSUBL, BIODIVSUB, BIODIVSUB2, BIODIVSUB3, BIODIVSUBA, BIODIVSUBF, BIODIVSUBM,
  BIODIVSUBG, BIODIVSUBC, BIODIVSUBS, MINPASTN/;

SET GBIDRAG(P)  General paid supports
 /GACRSUB, 
  ECOSUB,
  CATTLESUB, SOWHLTSUB/;

SET CROPACR(AS)  Land use: 1000 hectare
 /W-WHEAT, W-RAY, W-BARLEY, BARLEY, OATS, GRAINSIL, FEEDPEAS, W-RAPE, S-RAPE,
  POTATO, SUGAR, FORAGE1*FORAGE4, PASTURE1, PASTURE2, NEWFOR, OTHERCROPS, SALIX, LAY, LONGLAY,
  EW-WHEAT, EW-RAY, EBARLEY, EOATS, EFEEDPEAS, EW-RAPE, ES-RAPE, EPOTATO, ESUGAR,
  EFORAGE1*EFORAGE4,EPASTURE1, EPASTURE2, ENEWFOR, EOTHRCROPS, ELAY, ENFIX, ECOPIG, EPOULTRY,
  SPAREFOR, ICR, NOUSE, PPASTR, PPASTRB, PPASTRT, PPASTRN, PPASTRH, PPASTRHB, PPASTRHT,
  PPASTRHN, PPASTRALV, PPASTRFOR, PPASTRMOS, PPASTRLOW, PPASTRCHAL, PPASTRMEAD,
  SPAPASTR, SPAPASTRB, SPAPASTRT, SPAPASTRH, SPAPASTRHB, SPAPASTRHT, UPGRPAST, UPGRPASTH,
  CROPTOPAST, LVSTKIN, LVSTKOUT/;  

SET SELI(I)  Selected inputs
 /LABOR, NITROGEN, PHOSPHORUS, POTASSIUM, PESTICIDES, POWER/;

PARAMETER RTBL1(R,SR,PS,TH1)  Results for subregional products: 1000 tons;
RTBL1(R,SR,PS,TH1) = 0.0;
RTBL1(R,SR,PS,'PRODUCTION') $RSRPS(R,SR,PS) =
  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PS) LT 0)), -EAS(R,SR,AS,PS)*PRODSR.L(R,SR,AS));
RTBL1(R,SR,PS,'USE') $RSRPS(R,SR,PS) =
  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PS) GT 0)), EAS(R,SR,AS,PS)*PRODSR.L(R,SR,AS));
RTBL1(R,SR,PS,'DEMAND') $PSED(R,SR,PS) = DEMANDPS.L(R,SR,PS);
RTBL1(R,SR,PS,'FIXED-DEM') $PSFD(R,SR,PS) = PRODUCTSF.LO(R,SR,PS);
RTBL1(R,SR,PS,'PRICE') $RSRPS(R,SR,PS) = - PRODUCTSE.M(R,SR,PS) $PSED(R,SR,PS)
                                         - PRODUCTSF.M(R,SR,PS) $PSFD(R,SR,PS);
 
PARAMETER RTBL1B(SR,PRIMP)  Total production by production region;
RTBL1B(SR,PRIMP) = 0.0;
RTBL1B(SR,PRIMP) = SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PRIMP) LT 0)),
                         -EAS(R,SR,AS,PRIMP)*PRODSR.L(R,SR,AS)));

PARAMETER RTBL1B2(UPR,PRIMP)  Total production by FA region: 1000 ton;
RTBL1B2(UPR,PRIMP) = SUM(SR $UPRSR(UPR,SR), RTBL1B(SR,PRIMP));


PARAMETER RTBL1C(SR,P)  Gross production value by production region: Million SEK;
RTBL1C(SR,P) = 0.0;
RTBL1C(SR,PR) $PRIMP(PR) =
  SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PR) LT 0)),
                         -EAS(R,SR,AS,PR)*PRODSR.L(R,SR,AS)*
                            (-PRODUCTRE.M(R,PR) -PRODUCTRF.M(R,PR))));
RTBL1C(SR,PS) $PRIMP(PS) =
  SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PS) LT 0)),
                         -EAS(R,SR,AS,PS)*PRODSR.L(R,SR,AS)*
                            (-PRODUCTSE.M(R,SR,PS) -PRODUCTSF.M(R,SR,PS))));

PARAMETER RTBL1C2(UPR,P)  Gross production value by FA region: Million SEK;
RTBL1C2(UPR,P) = SUM(SR $UPRSR(UPR,SR), RTBL1C(SR,P));


PARAMETER RTBL1D(SR,P)  Net production value by production region: Million SEK;
RTBL1D(SR,P) = 0.0;
RTBL1D(SR,PR) $PRIMP(PR) =
  SUM(R $RSR(R,SR), SUM(AS $RSRAS(R,SR,AS),
                         -EAS(R,SR,AS,PR)*PRODSR.L(R,SR,AS)*
                            (-PRODUCTRE.M(R,PR) -PRODUCTRF.M(R,PR))));
RTBL1D(SR,PS) $PRIMP(PS) =
  SUM(R $RSR(R,SR), SUM(AS $RSRAS(R,SR,AS),
                         -EAS(R,SR,AS,PS)*PRODSR.L(R,SR,AS)*
                            (-PRODUCTSE.M(R,SR,PS) -PRODUCTSF.M(R,SR,PS))));

PARAMETER RTBL1E(SR,P)  Total support by production region: Million SEK;
RTBL1E(SR,P) = 0.0;
RTBL1E(SR,PN) $BIDRAG(PN) =
  SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PN) LT 0)),
                         -EAS(R,SR,AS,PN)*PRODSR.L(R,SR,AS)*
                            (-PRODUCTNE.M(PN) -PRODUCTNF.M(PN))));
RTBL1E(SR,PR) $BIDRAG(PR) =
  SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PR) LT 0)),
                         -EAS(R,SR,AS,PR)*PRODSR.L(R,SR,AS)*
                            (-PRODUCTRE.M(R,PR) -PRODUCTRF.M(R,PR))));
RTBL1E(SR,PS) $BIDRAG(PS) =
  SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PS) LT 0)),
                         -EAS(R,SR,AS,PS)*PRODSR.L(R,SR,AS)*
                            (-PRODUCTSE.M(R,SR,PS) -PRODUCTSF.M(R,SR,PS))));

PARAMETER RTBL2(R,PR,TH1)  Results for regional products;
RTBL2(R,PR,TH1) = 0.0;
RTBL2(R,PR,'PRODUCTION') $RPR(R,PR) =
  SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PR) LT 0)),
                         -EAS(R,SR,AS,PR)*PRODSR.L(R,SR,AS)))
  + SUM(CR $(RCR(R,CR) $(ECR(R,CR,PR) LT 0)), -ECR(R,CR,PR)*PROCR.L(R,CR));
RTBL2(R,PR,'USE') $RPR(R,PR) =
  SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PR) GT 0)),
                         EAS(R,SR,AS,PR)*PRODSR.L(R,SR,AS)))
  + SUM(CR $(RCR(R,CR) $(ECR(R,CR,PR) GT 0)), ECR(R,CR,PR)*PROCR.L(R,CR));
RTBL2(R,PR,'SHIP-IN') $RPR(R,PR) = SUM(RS $TIP(RS,R,PR), TRANIP.L(RS,R,PR));
RTBL2(R,PR,'SHIP-OUT') $RPR(R,PR) = SUM(RD $TIP(R,RD,PR), TRANIP.L(R,RD,PR));
RTBL2(R,PR,'DEMAND') $PRED(R,PR) = DEMANDPR.L(R,PR);
RTBL2(R,PR,'FIXED-DEM') $PRFD(R,PR) = PRODUCTRF.LO(R,PR);
RTBL2(R,PR,'IMPORT') $RPRIM(R,PR) = IMPORTPR.L(R,PR);
RTBL2(R,PR,'EXPORT') $RPREX(R,PR) = EXPORTRP.L(R,PR);
RTBL2(R,PR,'PRICE') $RPR(R,PR) = - PRODUCTRE.M(R,PR) $PRED(R,PR) - PRODUCTRF.M(R,PR) $PRFD(R,PR);

PARAMETER RTBL3(PN,TH1)  Results for national products;
RTBL3(PN,TH1) = 0.0;
RTBL3(PN,'PRODUCTION') =
  SUM(R,SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PN) LT 0)),
                               -EAS(R,SR,AS,PN)*PRODSR.L(R,SR,AS)))
        + SUM(CR $(RCR(R,CR) $(ECR(R,CR,PN) LT 0)), -ECR(R,CR,PN)*PROCR.L(R,CR)));
RTBL3(PN,'USE') =
  SUM(R,SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PN) GT 0)),
                                               EAS(R,SR,AS,PN)*PRODSR.L(R,SR,AS)))
                        + SUM(CR $(RCR(R,CR) $(ECR(R,CR,PN) GT 0)), ECR(R,CR,PN)*PROCR.L(R,CR)));
RTBL3(PN,'DEMAND') $PNED(PN) = DEMANDPN.L(PN);
RTBL3(PN,'FIXED-DEM') $PNFD(PN) = PRODUCTNF.LO(PN);
RTBL3(PN,'PRICE') = - PRODUCTNE.M(PN) $PNED(PN) - PRODUCTNF.M(PN) $PNFD(PN);
 
PARAMETER RTBL4(P,TH1)  National summary for all products;
RTBL4(P,TH1) = 0.0;
RTBL4(PS,'PRODUCTION') = SUM(R, SUM(SR $RSRPS(R,SR,PS), RTBL1(R,SR,PS,'PRODUCTION')));
RTBL4(PR,'PRODUCTION') = SUM(R $RPR(R,PR), RTBL2(R,PR,'PRODUCTION'));
RTBL4(PN,'PRODUCTION') = RTBL3(PN,'PRODUCTION');
RTBL4(PS,'USE') = SUM(R, SUM(SR $RSRPS(R,SR,PS), RTBL1(R,SR,PS,'USE')));
RTBL4(PR,'USE') = SUM(R $RPR(R,PR), RTBL2(R,PR,'USE'));
RTBL4(PN,'USE') = RTBL3(PN,'USE');
RTBL4(PR,'SHIPMENTS') = SUM(R $RPR(R,PR), RTBL2(R,PR,'SHIP-OUT'));
RTBL4(PS,'DEMAND') = SUM(R, SUM(SR $PSED(R,SR,PS), RTBL1(R,SR,PS,'DEMAND')));
RTBL4(PR,'DEMAND') = SUM(R $PRED(R,PR), RTBL2(R,PR,'DEMAND'));
RTBL4(PN,'DEMAND') $PNED(PN) = RTBL3(PN,'DEMAND');
RTBL4(PS,'FIXED-DEM') = SUM(R, SUM(SR $PSFD(R,SR,PS), RTBL1(R,SR,PS,'FIXED-DEM')));
RTBL4(PR,'FIXED-DEM') = SUM(R $PRFD(R,PR), RTBL2(R,PR,'FIXED-DEM')); 
RTBL4(PN,'FIXED-DEM') $PNFD(PN) = RTBL3(PN,'FIXED-DEM');
RTBL4(PR,'IMPORT') = SUM(R $RPR(R,PR), RTBL2(R,PR,'IMPORT'));
RTBL4(PR,'EXPORT') = SUM(R $RPR(R,PR), RTBL2(R,PR,'EXPORT'));
RTBL4(PS,'PRICE') =
  SUM(R, SUM(SR $(RSRPS(R,SR,PS) $(RTBL4(PS,'PRODUCTION') GT 0)),

             RTBL1(R,SR,PS,'PRICE')*RTBL1(R,SR,PS,'PRODUCTION')/RTBL4(PS,'PRODUCTION')));
RTBL4(PR,'PRICE') =
  SUM(R $(RPR(R,PR) $(RTBL4(PR,'PRODUCTION') GT 0)),
      RTBL2(R,PR,'PRICE')*RTBL2(R,PR,'PRODUCTION')/RTBL4(PR,'PRODUCTION'));
RTBL4(PN,'PRICE') = RTBL3(PN,'PRICE');
 
PARAMETER RTBL5(R,PS,SR)  Subregional product prices;
RTBL5(R,PS,SR) = 0.0;
RTBL5(R,PS,SR) = RTBL1(R,SR,PS,'PRICE');
 
PARAMETER RTBL6(PR,R)  Regional product prices;
RTBL6(PR,R) = 0.0;

RTBL6(PR,R) = RTBL2(R,PR,'PRICE');

PARAMETER RTBL6A(PR,R)  Regional consumtion;
RTBL6A(PR,R) = 0.0;

RTBL6A(PR,R) = RTBL2(R,PR,'DEMAND');

PARAMETER RTBL6B(*,R)  Regional consumtion;
RTBL6B('ENERGY',R) = RTBL2(R,'ENERGY','PRODUCTION') - RTBL2(R,'ENERGY','USE');
RTBL6B('PROTEIN',R) = RTBL2(R,'PROTEIN','PRODUCTION') - RTBL2(R,'PROTEIN','USE');
RTBL6B('PROTEINA',R) = RTBL2(R,'PROTEINA','PRODUCTION') - RTBL2(R,'PROTEINA','USE');
RTBL6B('FAT',R) = RTBL2(R,'FAT','PRODUCTION') - RTBL2(R,'FAT','USE');
RTBL6B('CARBOH',R) = RTBL2(R,'CARBOH','PRODUCTION') - RTBL2(R,'CARBOH','USE');
RTBL6B('FEEDGRAINU',R) = RTBL2(R,'FEEDGRAIN','USE');

 
PARAMETER RTBL7(R,SR,IS,TH1)  Results for subregional inputs;
RTBL7(R,SR,IS,TH1) = 0.0;

RTBL7(R,SR,IS,'PRODUCTION') $RSRIS(R,SR,IS) =
  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,IS) LT 0)), -EAS(R,SR,AS,IS)*PRODSR.L(R,SR,AS));
RTBL7(R,SR,IS,'USE') $RSRIS(R,SR,IS) =
  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,IS) GT 0)), EAS(R,SR,AS,IS)*PRODSR.L(R,SR,AS));
RTBL7(R,SR,IS,'SUPPLY') $ISES(R,SR,IS) = SUPPLYIS.L(R,SR,IS);
RTBL7(R,SR,IS,'FIXED-SUP') $ISFS(R,SR,IS) = INPUTSF.UP(R,SR,IS);
RTBL7(R,SR,IS,'PRICE') $RSRIS(R,SR,IS) = INPUTSE.M(R,SR,IS) $ISES(R,SR,IS)
                                         + INPUTSF.M(R,SR,IS) $ISFS(R,SR,IS);
 
PARAMETER RTBL7B(SR,I)  Use of some inputs;
RTBL7B(SR,I) $SELI(I) =
  SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,I) GT 0)),
                         EAS(R,SR,AS,I)*PRODSR.L(R,SR,AS)));

PARAMETER RTBL7B2(UPR,I)  Use of some inputs by FA region;
RTBL7B2(UPR,I) $SELI(I) =  SUM(SR $UPRSR(UPR,SR), RTBL7B(SR,I));

PARAMETER RTBL8(R,IR,TH1)  Results for regional inputs;
RTBL8(R,IR,TH1) = 0.0;
RTBL8(R,IR,'PRODUCTION') $RIR(R,IR) =
  SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,IR) LT 0)),
                         -EAS(R,SR,AS,IR)*PRODSR.L(R,SR,AS)))
  + SUM(CR $(RCR(R,CR) $(ECR(R,CR,IR) LT 0)), -ECR(R,CR,IR)*PROCR.L(R,CR));
RTBL8(R,IR,'USE') $RIR(R,IR) =
  SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,IR) GT 0)),
                         EAS(R,SR,AS,IR)*PRODSR.L(R,SR,AS)))
  + SUM(CR $(RCR(R,CR) $(ECR(R,CR,IR) GT 0)), ECR(R,CR,IR)*PROCR.L(R,CR));
RTBL8(R,IR,'SHIP-IN') $RIR(R,IR) = SUM(RS $TIP(RS,R,IR), TRANIP.L(RS,R,IR));
RTBL8(R,IR,'SHIP-OUT') $RIR(R,IR) = SUM(RD $TIP(R,RD,IR), TRANIP.L(R,RD,IR));
RTBL8(R,IR,'SUPPLY') $IRES(R,IR) = SUPPLYIR.L(R,IR);
RTBL8(R,IR,'FIXED-SUP') $IRFS(R,IR) = INPUTRF.UP(R,IR);

RTBL8(R,IR,'PRICE') $RIR(R,IR) = INPUTRE.M(R,IR) $IRES(R,IR) + INPUTRF.M(R,IR) $IRFS(R,IR);
 
PARAMETER RTBL9(IN,TH1)  Results for national inputs;
RTBL9(IN,TH1) = 0.0;
RTBL9(IN,'PRODUCTION') =
  SUM(R,SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,IN) LT 0)),
                               -EAS(R,SR,AS,IN)*PRODSR.L(R,SR,AS)))
        + SUM(CR $(RCR(R,CR) $(ECR(R,CR,IN) LT 0)), -ECR(R,CR,IN)*PROCR.L(R,CR)));
RTBL9(IN,'USE') =
  SUM(R,SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,IN) GT 0)),
                                               EAS(R,SR,AS,IN)*PRODSR.L(R,SR,AS)))
                        + SUM(CR $(RCR(R,CR) $(ECR(R,CR,IN) GT 0)), ECR(R,CR,IN)*PROCR.L(R,CR)));
RTBL9(IN,'SUPPLY') $INES(IN) = SUPPLYIN.L(IN);
RTBL9(IN,'FIXED-SUP') $INFS(IN) = INPUTNF.UP(IN);
RTBL9(IN,'PRICE') = INPUTNE.M(IN) $INES(IN) + INPUTNF.M(IN) $INFS(IN);
 
PARAMETER RTBL9A(*,*)  Summary for production and inputs;
RTBL9A(SR,'AGRLAND')   = SUM(R, RTBL7(R,SR,'CROPLAND','USE')
   + RTBL7(R,SR,'PRMPAST','USE') + RTBL7(R,SR,'PRMPASTB','USE') + RTBL7(R,SR,'PRMPASTT','USE')
   + RTBL7(R,SR,'PRMPASTN','USE') + RTBL7(R,SR,'PRMPASTH','USE') + RTBL7(R,SR,'PRMPASTHB','USE')
   + RTBL7(R,SR,'PRMPASTHT','USE') + RTBL7(R,SR,'PRMPASTHN','USE')+ RTBL7(R,SR,'PRMALV','USE')
   + RTBL7(R,SR,'PRMFOR','USE') + RTBL7(R,SR,'PRMMOS','USE') + RTBL7(R,SR,'PRMLOW','USE')
   + RTBL7(R,SR,'PRMCHAL','USE') + RTBL7(R,SR,'PRMMEAD','USE'));
RTBL9A(SR,'GROSSPROD') = SUM(P, RTBL1C(SR,P));
RTBL9A(SR,'NETPROD')   = SUM(P, RTBL1D(SR,P));
RTBL9A(SR,'DIRECTPAYM')= SUM(P, RTBL1E(SR,P));
RTBL9A(SR,'GENERALSUP')= SUM(P $GBIDRAG(P), RTBL1E(SR,P));
RTBL9A(SR,SELI)        = RTBL7B(SR,SELI);
RTBL9A('SWEDEN','AGRLAND')    = SUM(SR, RTBL9A(SR,'AGRLAND'));
RTBL9A('SWEDEN','GROSSPROD')  = SUM(SR, SUM(P, RTBL1C(SR,P)));
RTBL9A('SWEDEN','NETPROD')    = SUM(SR, SUM(P, RTBL1D(SR,P)));
RTBL9A('SWEDEN','DIRECTPAYM') = SUM(SR, SUM(P, RTBL1E(SR,P)));
RTBL9A('SWEDEN','GENERALSUP') = SUM(SR, SUM(P $GBIDRAG(P), RTBL1E(SR,P)));
RTBL9A('SWEDEN',SELI)         = SUM(SR, RTBL7B(SR,SELI));

PARAMETER RTBL9B(*,*)  Production and inputs per hour;

RTBL9B(SR,'AGRLAND')   = RTBL9A(SR,'AGRLAND')/RTBL9A(SR,'LABOR');
RTBL9B(SR,'GROSSPROD') = RTBL9A(SR,'GROSSPROD')/RTBL9A(SR,'LABOR');
RTBL9B(SR,'NETPROD')   = RTBL9A(SR,'NETPROD')/RTBL9A(SR,'LABOR');
RTBL9B(SR,'DIRECTPAYM')= RTBL9A(SR,'DIRECTPAYM')/RTBL9A(SR,'LABOR');
RTBL9B(SR,SELI)        = RTBL9A(SR,SELI)/RTBL9A(SR,'LABOR');
RTBL9B('SWEDEN','AGRLAND')   = RTBL9A('SWEDEN','AGRLAND')/RTBL9A('SWEDEN','LABOR');
RTBL9B('SWEDEN','GROSSPROD') = RTBL9A('SWEDEN','GROSSPROD')/RTBL9A('SWEDEN','LABOR');

RTBL9B('SWEDEN','NETPROD')   = RTBL9A('SWEDEN','NETPROD')/RTBL9A('SWEDEN','LABOR');
RTBL9B('SWEDEN','DIRECTPAYM')= RTBL9A('SWEDEN','DIRECTPAYM')/RTBL9A('SWEDEN','LABOR');
RTBL9B('SWEDEN',SELI)        = RTBL9A('SWEDEN',SELI)/RTBL9A('SWEDEN','LABOR');

PARAMETER RTBL9C(*,*)  Production and inputs per hectare of agricultural land;
RTBL9C(SR,'AGRLAND')   = RTBL9A(SR,'AGRLAND')/RTBL9A(SR,'AGRLAND');
RTBL9C(SR,'GROSSPROD') = RTBL9A(SR,'GROSSPROD')/RTBL9A(SR,'AGRLAND');
RTBL9C(SR,'NETPROD')   = RTBL9A(SR,'NETPROD')/RTBL9A(SR,'AGRLAND');
RTBL9C(SR,'DIRECTPAYM')= RTBL9A(SR,'DIRECTPAYM')/RTBL9A(SR,'AGRLAND');
RTBL9C(SR,SELI)        = RTBL9A(SR,SELI)/RTBL9A(SR,'AGRLAND');
RTBL9C('SWEDEN','AGRLAND')   = RTBL9A('SWEDEN','AGRLAND')/RTBL9A('SWEDEN','AGRLAND');
RTBL9C('SWEDEN','GROSSPROD') = RTBL9A('SWEDEN','GROSSPROD')/RTBL9A('SWEDEN','AGRLAND');

RTBL9C('SWEDEN','NETPROD')   = RTBL9A('SWEDEN','NETPROD')/RTBL9A('SWEDEN','AGRLAND');

RTBL9C('SWEDEN','DIRECTPAYM')= RTBL9A('SWEDEN','DIRECTPAYM')/RTBL9A('SWEDEN','AGRLAND');
RTBL9C('SWEDEN',SELI)        = RTBL9A('SWEDEN',SELI)/RTBL9A('SWEDEN','AGRLAND');

PARAMETER RTBL10(I,TH1)  National summary for all inputs;
RTBL10(I,TH1) = 0.0;

RTBL10(IS,'PRODUCTION') = SUM(R, SUM(SR $RSRIS(R,SR,IS), RTBL7(R,SR,IS,'PRODUCTION')));
RTBL10(IR,'PRODUCTION') = SUM(R $RIR(R,IR), RTBL8(R,IR,'PRODUCTION'));
RTBL10(IN,'PRODUCTION') = RTBL9(IN,'PRODUCTION');
RTBL10(IS,'USE') = SUM(R, SUM(SR $RSRIS(R,SR,IS), RTBL7(R,SR,IS,'USE')));
RTBL10(IR,'USE') = SUM(R $RIR(R,IR), RTBL8(R,IR,'USE'));
RTBL10(IN,'USE') = RTBL9(IN,'USE');
RTBL10(IR,'SHIPMENTS') = SUM(R $RIR(R,IR), RTBL8(R,IR,'SHIP-OUT'));
RTBL10(IS,'SUPPLY') = SUM(R, SUM(SR $ISES(R,SR,IS), RTBL7(R,SR,IS,'SUPPLY')));
RTBL10(IR,'SUPPLY') = SUM(R $IRES(R,IR), RTBL8(R,IR,'SUPPLY'));
RTBL10(IN,'SUPPLY') $INES(IN) = RTBL9(IN,'SUPPLY');
RTBL10(IS,'FIXED-SUP') = SUM(R, SUM(SR $RSRIS(R,SR,IS), RTBL7(R,SR,IS,'FIXED-SUP')));
RTBL10(IR,'FIXED-SUP') = SUM(R $IRFS(R,IR), RTBL8(R,IR,'FIXED-SUP'));
RTBL10(IN,'FIXED-SUP') $INFS(IN) = RTBL9(IN,'FIXED-SUP');
RTBL10(IS,'PRICE') =
  SUM(R, SUM(SR $(RSRIS(R,SR,IS) $(RTBL10(IS,'USE') GT 0)),
             RTBL7(R,SR,IS,'PRICE')*RTBL7(R,SR,IS,'USE')/RTBL10(IS,'USE')));
RTBL10(IR,'PRICE') =
  SUM(R $(RIR(R,IR) $(RTBL10(IR,'USE') GT 0)),
      RTBL8(R,IR,'PRICE')*RTBL8(R,IR,'USE')/RTBL10(IR,'USE'));
RTBL10(IN,'PRICE') = RTBL9(IN,'PRICE');
 

PARAMETER RTBL11(R,IS,SR)  Subregional input prices;
RTBL11(R,IS,SR) = 0.0;
RTBL11(R,IS,SR) = RTBL7(R,SR,IS,'PRICE');
 
PARAMETER RTBL12(IR,R)  Regional input prices;
RTBL12(IR,R) = 0.0;
RTBL12(IR,R) = RTBL8(R,IR,'PRICE');

 
PARAMETER RTBL13(R,AS,SR)  Subregional production activities;
RTBL13(R,AS,SR) = 0.0;


RTBL13(R,AS,SR) $RSRAS(R,SR,AS) = PRODSR.L(R,SR,AS);

PARAMETER RTBL13C(CROPACR,SR)  Crop acreage by subregion: 1000 ha;
RTBL13C(CROPACR,SR) = 0.0;
RTBL13C(CROPACR,SR) = SUM(R $RSRAS(R,SR,CROPACR), PRODSR.L(R,SR,CROPACR));

PARAMETER RTBL13C2(CROPACR, UPR)  Crop acreage by Output-region;
RTBL13C2(CROPACR,UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13C(CROPACR, SR)); 

PARAMETER RTBL13D(LIVESTOCK,SR)  Numbers of livestock by subregion: 1000 Head;
RTBL13D(LIVESTOCK,SR) = 0.0;
RTBL13D(LIVESTOCK,SR) = SUM(R $RSRAS(R,SR, LIVESTOCK), PRODSR.L(R,SR,LIVESTOCK));

PARAMETER RTBL13D2(LIVESTOCK, UPR)  Numbers of livestock by Output-region;
RTBL13D2(LIVESTOCK,UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13D(LIVESTOCK, SR)); 

PARAMETER RTBL13B(SR,AS)  Production activities by subregion;
RTBL13B(SR,AS) = 0.0;

RTBL13B(SR,AS) = SUM(R $RSRAS(R,SR,AS), PRODSR.L(R,SR,AS));

PARAMETER RTBL13E(*,*)  Crop acreage and numbers of livestock by subregion;
RTBL13E('VALL',SR)       = RTBL13C('FORAGE1',SR)+RTBL13C('FORAGE2',SR)+RTBL13C('FORAGE3',SR)+
                         RTBL13C('FORAGE4',SR)+RTBL13C('PASTURE1',SR)+RTBL13C('PASTURE2',SR)+
                         RTBL13C('EFORAGE1',SR)+RTBL13C('EFORAGE2',SR)+RTBL13C('EFORAGE3',SR)+
                         RTBL13C('EFORAGE4',SR)+RTBL13C('EPASTURE1',SR)+RTBL13C('EPASTURE2',SR)+
                         RTBL13C('ENEWFOR',SR)+
                         RTBL13C('NEWFOR',SR)+RTBL13C('SPAREFOR',SR);
RTBL13E('HOSTSAD',SR)    = RTBL13C('W-WHEAT',SR)+RTBL13C('W-RAY',SR)+RTBL13C('W-BARLEY',SR)+
                            RTBL13C('GRAINSIL',SR)/2
                         +RTBL13C('EW-WHEAT',SR)+RTBL13C('EW-RAY',SR);
RTBL13E('VARSAD',SR)     = RTBL13C('BARLEY',SR)+RTBL13C('OATS',SR)+RTBL13C('GRAINSIL',SR)/2
                         +RTBL13C('EBARLEY',SR)+RTBL13C('EOATS',SR);  
RTBL13E('OLJEVAXT',SR)   = RTBL13C('W-RAPE',SR)+RTBL13C('S-RAPE',SR)
                         +RTBL13C('EW-RAPE',SR)+RTBL13C('ES-RAPE',SR);
RTBL13E('UTTAG',SR)      = RTBL13C('LAY',SR)+RTBL13C('LONGLAY',SR)+RTBL13C('NOUSE',SR)
                         +RTBL13C('ELAY',SR)+RTBL13C('ENFIX',SR);
RTBL13E('OVGRODOR',SR)   = RTBL13C('POTATO',SR)+RTBL13C('SUGAR',SR)+RTBL13C('OTHERCROPS',SR)+
                         RTBL13C('FEEDPEAS',SR)+RTBL13C('SALIX',SR)+
                         RTBL13C('EFEEDPEAS',SR)+RTBL13C('EPOTATO',SR)+RTBL13C('ESUGAR',SR)+
                         RTBL13C('EOTHRCROPS',SR)+RTBL13C('ECOPIG',SR)+RTBL13C('EPOULTRY',SR)+
                         RTBL13C('ICR',SR);
RTBL13E('AKER',SR)       = RTBL13E('VALL',SR)+RTBL13E('HOSTSAD',SR)+RTBL13E('VARSAD',SR)+
                         RTBL13E('OLJEVAXT',SR)+RTBL13E('UTTAG',SR)+RTBL13E('OVGRODOR',SR);
RTBL13E('BETESMARK',SR)  = RTBL13C('PPASTR',SR)+RTBL13C('PPASTRT',SR)+RTBL13C('PPASTRN',SR)+
                         RTBL13C('PPASTRH',SR)+RTBL13C('PPASTRHT',SR)+RTBL13C('PPASTRHN',SR)+
                         RTBL13C('PPASTRALV',SR)+RTBL13C('PPASTRFOR',SR)+RTBL13C('PPASTRMOS',SR)+
                         RTBL13C('PPASTRLOW',SR)+RTBL13C('PPASTRCHAL',SR)+RTBL13C('PPASTRMEAD',SR);
RTBL13E('MJOLKKO',SR)    = RTBL13D('DCOW1',SR)+RTBL13D('DCOW2',SR)+RTBL13D('DCOW3',SR)+
                           RTBL13D('DCOW4',SR)
                           +RTBL13D('EDCOW1',SR)+RTBL13D('EDCOW2',SR)+RTBL13D('EDCOW3',SR);

RTBL13E('DIKO',SR)       = RTBL13D('BEEFCATTLE',SR) + RTBL13D('BEEFCATTL2',SR)
                           + RTBL13D('EBEEFCATT',SR) + RTBL13D('EBEEFCAT2',SR);
RTBL13E('REKKVIGA1',SR)  = RTBL13D('HEIFER',SR) + 
                           RTBL13D('EHEIFER',SR) + 
                           RTBL13E('DIKO',SR)*0.2*1.1; 
RTBL13E('REKKVIGA2',SR)  = RTBL13D('HEIFER',SR)*13/12 +
                           RTBL13D('EHEIFER',SR)*13/12 +
                           RTBL13E('DIKO',SR)*0.2*1.1; 
RTBL13E('SLAKTKVIG1',SR) = RTBL13D('SLGHHEIFER',SR)*12/12 +
                           RTBL13D('ESLGHHEIF',SR)*12/12 + 
                           RTBL13E('DIKO',SR)*0.2*1.1*12/12; 
RTBL13E('SLAKTKVIG2',SR) = RTBL13D('SLGHHEIFER',SR)*16.75/12 +
                           RTBL13D('ESLGHHEIF',SR)*16.75/12 + 
                           RTBL13E('DIKO',SR)*0.2*1.1*16.75/12; 
RTBL13E('TJUR1',SR)      = RTBL13D('DAIRYBULL1',SR)*12/12 +
                           RTBL13D('EDBULL1',SR)*12/12 + 
                           RTBL13D('BEEFCATTLE',SR)*0.4*1.1 + RTBL13D('EBEEFCATT',SR)*0.4*1.1;
RTBL13E('TJUR2',SR)      = RTBL13D('DAIRYBULL1',SR)*8.7/12  +
                           RTBL13D('EDBULL1',SR)*8.7/12  + 
                           RTBL13D('BEEFCATTLE',SR)*0.4*1.1*0.725 +
                           RTBL13D('EBEEFCATT',SR)*0.4*1.1*0.725;
RTBL13E('STUT1',SR)      = RTBL13D('DAIRYBULL2',SR)*12/12
                           + RTBL13D('EDBULL2',SR)*12/12 
                           + RTBL13D('BEEFCATTL2',SR)*0.4*1.1 + RTBL13D('EBEEFCAT2',SR)*0.4*1.1;
RTBL13E('STUT2',SR)      = RTBL13D('DAIRYBULL2',SR)*16.75/12
                           + RTBL13D('EDBULL2',SR)*16.75/12 
                           + RTBL13D('BEEFCATTL2',SR)*16.75/12*0.4*1.1
                           + RTBL13D('EBEEFCAT2',SR)*16.75/12*0.4*1.1;
RTBL13E('SUGGA',SR)      = RTBL13D('SOW1',SR)
                           + RTBL13D('ECOPIG',SR);
*RTBL13E('SLAKTSVIN',SR)  = RTBL13D('SLGHSWINE1',SR)*PRODCOS('SLGHSWINE1','SWINEFAC',SR)
*                          + RTBL13D('ECOPIG',SR)*20*0.4;

RTBL13E('GRAINPROD',SR)  =  SUM(R $RSR(R,SR), 
                                  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,'BREADGRAIN') LT 0)),
                                    -EAS(R,SR,AS,'BREADGRAIN')*PRODSR.L(R,SR,AS)) +
                                  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,'COARSGRAIN') LT 0)),
                                    -EAS(R,SR,AS,'COARSGRAIN')*PRODSR.L(R,SR,AS)));
RTBL13E('BEEFPROD',SR)   =  SUM(R $RSR(R,SR), 
                                  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,'SLGHBEEF') LT 0)),
                                    -EAS(R,SR,AS,'SLGHBEEF')*PRODSR.L(R,SR,AS)));
RTBL13E('NLACKAGE',SR)  =  SUM(R $RSRIS(R,SR,'NLEAKAGE'), RTBL7(R,SR,'NLEAKAGE','USE'));
RTBL13E('PLACKAGE',SR)  =  SUM(R $RSRIS(R,SR,'PLEAKAGE'), RTBL7(R,SR,'PLEAKAGE','USE'));
RTBL13E('DIREKTBET',SR)  =  RTBL9A(SR,'DIRECTPAYM');
RTBL13E('AE&DB',SR)      =  RTBL9A(SR,'GENERALSUP');
RTBL13E('N-MANURE',SR)   =  SUM(R $RSR(R,SR), 
                                  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,'NITROGEN') LT 0)),
                                    -EAS(R,SR,AS,'NITROGEN')*PRODSR.L(R,SR,AS)));
RTBL13E('N-USE',SR)      =  SUM(R $RSR(R,SR), 
                                  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,'NITROGEN') GT 0)),
                                    EAS(R,SR,AS,'NITROGEN')*PRODSR.L(R,SR,AS)));
RTBL13E('N-BOUGHT',SR)   =  SUM(R $(RSR(R,SR) 
                          $(SUM(AS $RSRAS(R,SR,AS), EAS(R,SR,AS,'NITROGEN')*PRODSR.L(R,SR,AS)) GT 0)), 
                                   SUM(AS $RSRAS(R,SR,AS), EAS(R,SR,AS,'NITROGEN')*PRODSR.L(R,SR,AS)));
RTBL13E('P-MANURE',SR)   =  SUM(R $RSR(R,SR), 
                                  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,'PHOSPHORUS') LT 0)),
                                    -EAS(R,SR,AS,'PHOSPHORUS')*PRODSR.L(R,SR,AS)));
RTBL13E('P-USE',SR)      =  SUM(R $RSR(R,SR), 
                                  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,'PHOSPHORUS') GT 0)),
                                    EAS(R,SR,AS,'PHOSPHORUS')*PRODSR.L(R,SR,AS)));
RTBL13E('P-BOUGHT',SR)   =  SUM(R $(RSR(R,SR) 
                         $(SUM(AS $RSRAS(R,SR,AS), EAS(R,SR,AS,'PHOSPHORUS')*PRODSR.L(R,SR,AS)) GT 0)), 
                                 SUM(AS $RSRAS(R,SR,AS), EAS(R,SR,AS,'PHOSPHORUS')*PRODSR.L(R,SR,AS)));
RTBL13E('K-MANURE',SR)   =  SUM(R $RSR(R,SR), 
                                  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,'POTASSIUM') LT 0)),
                                    -EAS(R,SR,AS,'POTASSIUM')*PRODSR.L(R,SR,AS)));
RTBL13E('K-USE',SR)      =  SUM(R $RSR(R,SR), 
                                  SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,'POTASSIUM') GT 0)),
                                    EAS(R,SR,AS,'POTASSIUM')*PRODSR.L(R,SR,AS)));
RTBL13E('K-BOUGHT',SR)   =  SUM(R $(RSR(R,SR) 
                          $(SUM(AS $RSRAS(R,SR,AS), EAS(R,SR,AS,'POTASSIUM')*PRODSR.L(R,SR,AS)) GT 0)), 
                                  SUM(AS $RSRAS(R,SR,AS), EAS(R,SR,AS,'POTASSIUM')*PRODSR.L(R,SR,AS)));

* More parameters after RTBL20

RTBL13E('VALL','RIKET')     = SUM(SR, RTBL13E('VALL',SR));
RTBL13E('HOSTSAD','RIKET')  = SUM(SR, RTBL13E('HOSTSAD',SR));
RTBL13E('VARSAD','RIKET')   = SUM(SR, RTBL13E('VARSAD',SR));
RTBL13E('OLJEVAXT','RIKET') = SUM(SR, RTBL13E('OLJEVAXT',SR));
RTBL13E('UTTAG','RIKET')    = SUM(SR, RTBL13E('UTTAG',SR));
RTBL13E('OVGRODOR','RIKET') = SUM(SR, RTBL13E('OVGRODOR',SR));
RTBL13E('AKER','RIKET')     = SUM(SR, RTBL13E('AKER',SR));
RTBL13E('BETESMARK','RIKET')= SUM(SR, RTBL13E('BETESMARK',SR));
RTBL13E('MJOLKKO','RIKET')  = SUM(SR, RTBL13E('MJOLKKO',SR));
RTBL13E('DIKO','RIKET')     = SUM(SR, RTBL13E('DIKO',SR));
RTBL13E('REKKVIGA1','RIKET')  = SUM(SR, RTBL13E('REKKVIGA1',SR));
RTBL13E('REKKVIGA2','RIKET')  = SUM(SR, RTBL13E('REKKVIGA2',SR));
RTBL13E('SLAKTKVIG1','RIKET') = SUM(SR, RTBL13E('SLAKTKVIG1',SR));
RTBL13E('SLAKTKVIG2','RIKET') = SUM(SR, RTBL13E('SLAKTKVIG2',SR));
RTBL13E('TJUR1','RIKET')    = SUM(SR, RTBL13E('TJUR1',SR));
RTBL13E('TJUR2','RIKET')    = SUM(SR, RTBL13E('TJUR2',SR));
RTBL13E('STUT1','RIKET')    = SUM(SR, RTBL13E('STUT1',SR));
RTBL13E('STUT2','RIKET')    = SUM(SR, RTBL13E('STUT2',SR));
RTBL13E('SUGGA','RIKET')    = SUM(SR, RTBL13E('SUGGA',SR));
RTBL13E('SLAKTSVIN','RIKET')= SUM(SR, RTBL13E('SLAKTSVIN',SR));
RTBL13E('GRAINPROD','RIKET')= SUM(SR, RTBL13E('GRAINPROD',SR));
RTBL13E('BEEFPROD','RIKET') = SUM(SR, RTBL13E('BEEFPROD',SR));
*RTBL13E('N-LACKAGE','RIKET')= SUM(SR, RTBL13E('N-LACKAGE',SR));
RTBL13E('DIREKTBET','RIKET')= SUM(SR, RTBL13E('DIREKTBET',SR));
RTBL13E('AE&DB','RIKET')    = SUM(SR, RTBL13E('AE&DB',SR));
RTBL13E('N-MANURE','RIKET') = SUM(SR, RTBL13E('N-MANURE',SR));
RTBL13E('N-USE','RIKET') = SUM(SR, RTBL13E('N-USE',SR));
RTBL13E('N-BOUGHT','RIKET') = SUM(SR, RTBL13E('N-BOUGHT',SR));
RTBL13E('P-MANURE','RIKET') = SUM(SR, RTBL13E('P-MANURE',SR));
RTBL13E('P-USE','RIKET') = SUM(SR, RTBL13E('P-USE',SR));
RTBL13E('P-BOUGHT','RIKET') = SUM(SR, RTBL13E('P-BOUGHT',SR));
RTBL13E('K-MANURE','RIKET') = SUM(SR, RTBL13E('K-MANURE',SR));
RTBL13E('K-USE','RIKET') = SUM(SR, RTBL13E('K-USE',SR));
RTBL13E('K-BOUGHT','RIKET') = SUM(SR, RTBL13E('K-BOUGHT',SR));
* More parameters after RTBL20
 
PARAMETER RTBL14(AS,R)  Production activities by region;
RTBL14(AS,R) = 0.0;
RTBL14(AS,R) = SUM(SR $RSRAS(R,SR,AS), PRODSR.L(R,SR,AS));
 
PARAMETER RTBL15(AS)  National totals for production activities;
RTBL15(AS) = 0.0;
RTBL15(AS) = SUM(R, SUM(SR $RSRAS(R,SR,AS), PRODSR.L(R,SR,AS)));
 
SET TH3  Column headers for net profit tables
 /PRODUCTS, SUPPORT, REVENUE, VARCOST, NETPROFIT/;

PARAMETER RTBL16(SR,CROPS2, TH3) Revenue - costs and net profit for crop activities;

RTBL16(SR,CROPS2,'REVENUE') = SUM(R $RSRAS(R,SR,CROPS2), BIS(R,SR,'CROPLAND','MAX') * 
 (SUM(PS $RSRPS(R,SR,PS), EAS(R,SR,CROPS2,PS) * 
                          (PRODUCTSE.M(R,SR,PS) $PSED(R,SR,PS) + PRODUCTSF.M(R,SR,PS) $PSFD(R,SR,PS)))
     + SUM(PR $RPR(R,PR), EAS(R,SR,CROPS2,PR) * 
                          (PRODUCTRE.M(R,PR) $PRED(R,PR) + PRODUCTRF.M(R,PR) $PRFD(R,PR)))
 ))/SUM(R $RSR(R,SR), BIS(R,SR,'CROPLAND','MAX'));
RTBL16(SR,CROPS2,'SUPPORT') = SUM(R $RSRAS(R,SR,CROPS2), BIS(R,SR,'CROPLAND','MAX') * 
 SUM(SUPPORTS $RSRPS(R,SR,SUPPORTS), EAS(R,SR,CROPS2,SUPPORTS) * 
     (PRODUCTSE.M(R,SR,SUPPORTS) $PSED(R,SR,SUPPORTS) 
      + PRODUCTSF.M(R,SR,SUPPORTS) $PSFD(R,SR, SUPPORTS))))
 /SUM(R $RSR(R,SR), BIS(R,SR,'CROPLAND','MAX'));
RTBL16(SR,CROPS2,'PRODUCTS') = RTBL16(SR,CROPS2,'REVENUE') - RTBL16(SR,CROPS2,'SUPPORT');
RTBL16(SR,CROPS2,'VARCOST') = SUM(R $RSRAS(R,SR,CROPS2), BIS(R,SR,'CROPLAND','MAX') * 
 SUM(IR $RIR(R,IR), EAS(R,SR,CROPS2,IR) * 
                          (INPUTRE.M(R,IR) $IRES(R,IR) + INPUTRF.M(R,IR) $IRFS(R,IR))))

 /SUM(R $RSR(R,SR), BIS(R,SR,'CROPLAND','MAX'));

RTBL16(SR,CROPS2,'NETPROFIT') = RTBL16(SR,CROPS2,'REVENUE') - RTBL16(SR,CROPS2,'VARCOST');

PARAMETER RTBL17(SR,LIVESTOCK, TH3) Revenue - costs and net profit for livestock activities;

RTBL17(SR,LIVESTOCK,'REVENUE') = SUM(R $RSRAS(R,SR,LIVESTOCK), BIS(R,SR,'CROPLAND','MAX') * 
 (SUM(PS $RSRPS(R,SR,PS), EAS(R,SR,LIVESTOCK,PS) * 
                          (PRODUCTSE.M(R,SR,PS) $PSED(R,SR,PS) + PRODUCTSF.M(R,SR,PS) $PSFD(R,SR,PS)))
     + SUM(PR $RPR(R,PR), EAS(R,SR,LIVESTOCK,PR) * 
                          (PRODUCTRE.M(R,PR) $PRED(R,PR) + PRODUCTRF.M(R,PR) $PRFD(R,PR)))
 ))/SUM(R $RSR(R,SR), BIS(R,SR,'CROPLAND','MAX'));
RTBL17(SR,LIVESTOCK,'SUPPORT') = SUM(R $RSRAS(R,SR,LIVESTOCK), BIS(R,SR,'CROPLAND','MAX') * 
 SUM(SUPPORTS $RSRPS(R,SR,SUPPORTS), EAS(R,SR,LIVESTOCK,SUPPORTS) * 
     (PRODUCTSE.M(R,SR,SUPPORTS) $PSED(R,SR,SUPPORTS) 
      + PRODUCTSF.M(R,SR,SUPPORTS) $PSFD(R,SR, SUPPORTS))))
 /SUM(R $RSR(R,SR), BIS(R,SR,'CROPLAND','MAX'));

RTBL17(SR,LIVESTOCK,'PRODUCTS') = RTBL17(SR,LIVESTOCK,'REVENUE') - RTBL17(SR,LIVESTOCK,'SUPPORT');
RTBL17(SR,LIVESTOCK,'VARCOST') = SUM(R $RSRAS(R,SR,LIVESTOCK), BIS(R,SR,'CROPLAND','MAX') * 
 SUM(IR $RIR(R,IR), EAS(R,SR,LIVESTOCK,IR) * 
                          (INPUTRE.M(R,IR) $IRES(R,IR) + INPUTRF.M(R,IR) $IRFS(R,IR))))
 /SUM(R $RSR(R,SR), BIS(R,SR,'CROPLAND','MAX'));
RTBL17(SR,LIVESTOCK,'NETPROFIT') = RTBL17(SR,LIVESTOCK,'REVENUE') - RTBL17(SR,LIVESTOCK,'VARCOST');

* DISPLAY RTBL'S
 
OPTION RTBL4:3:1:1; DISPLAY $OC('PRODUCTS')
'For the national summary, quantities are summed over subregions and regions',
'as appropriate. Prices for subregional and regional products are weighted',
'averages with relative quantities produced as the weights.',RTBL4;

OPTION RTBL10:3:1:1; DISPLAY $OC('INPUTS')

'For the national summary, quantities are summed over subregions and regions',
'as appropriate. Prices for subregional and regional inputs are weighted',
'averages with relative quantities used as the weights. For such inputs, the',
'average price may be positive although total use is less than total supply.',RTBL10;

* --- Test
*SCALAR MILKBAL Difference in milk transfere balans (SEK per kg);
*       MILKBAL =(RTBL4('DPTRANR','PRODUCTION') - RTBL10('DPTRANC','USE'))/RTBL4('MILK','PRODUCTION');
*DISPLAY MILKBAL;

SCALAR MILKBAL Difference in milk transfere balans (SEK per kg);
MILKBAL = NA;
MILKBAL$(RTBL4('MILK','PRODUCTION') <> 0) =
   (RTBL4('DPTRANR','PRODUCTION') - RTBL10('DPTRANC','USE'))
 / RTBL4('MILK','PRODUCTION');
DISPLAY MILKBAL;
* --- end test

OPTION RTBL15:3:0:1; DISPLAY $OC('PRODACT') RTBL15;


PARAMETER FIXPRIS(PRIMP) 
 /BREADGRAIN  1.100, COARSGRAIN  1.119, FEEDGRAIN  1.142, OILGRAIN  1.790, POTATOES  0.561,
  SUGARBEET   0.420, SILAGE      1.004, GRASSPASTR 0.623, MILK      2.859, SLGHBEEF 25.375,
  SLGHPORK   13.766, SLGHPLTRY   7.435, SLGHSHEEP 25.770, EGG       8.314/;

PARAMETER RTBL20(SR,*)  Miscellaneous by production region;
RTBL20(SR,'GPV') = 
    SUM(PR $PRIMP(PR), SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PR) LT 0)),
                         -EAS(R,SR,AS,PR)*PRODSR.L(R,SR,AS)*
                            (-PRODUCTRE.M(R,PR) -PRODUCTRF.M(R,PR))))) +
    SUM(PS $PRIMP(PS), SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PS) LT 0)),
                         -EAS(R,SR,AS,PS)*PRODSR.L(R,SR,AS)*
                            (-PRODUCTSE.M(R,SR,PS) -PRODUCTSF.M(R,SR,PS)))));
RTBL20(SR,'NPV') = 
    SUM(PR $PRIMP(PR), SUM(R $RSR(R,SR), SUM(AS $RSRAS(R,SR,AS),
                         -EAS(R,SR,AS,PR)*PRODSR.L(R,SR,AS)*

                            (-PRODUCTRE.M(R,PR) -PRODUCTRF.M(R,PR))))) +
    SUM(PS $PRIMP(PS), SUM(R $RSR(R,SR), SUM(AS $RSRAS(R,SR,AS),
                         -EAS(R,SR,AS,PS)*PRODSR.L(R,SR,AS)*
                            (-PRODUCTSE.M(R,SR,PS) -PRODUCTSF.M(R,SR,PS)))));
RTBL20(SR,'GPVF') = 
    SUM(PRIMP, SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,PRIMP) LT 0)),
                         -EAS(R,SR,AS,PRIMP)*PRODSR.L(R,SR,AS)*FIXPRIS(PRIMP))));
RTBL20(SR,'NPVF') = 
    SUM(PRIMP, SUM(R $RSR(R,SR), SUM(AS $RSRAS(R,SR,AS),
                         -EAS(R,SR,AS,PRIMP)*PRODSR.L(R,SR,AS)*FIXPRIS(PRIMP))));
RTBL20(SR,'LABOUR') =

  SUM(R $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS) $(EAS(R,SR,AS,'LABOR') GT 0)),
                         EAS(R,SR,AS,'LABOR')*PRODSR.L(R,SR,AS)));
RTBL20(SR,'LANDRENTC') =
  SUM(R $RSR(R,SR), RTBL7(R,SR,'CROPLAND','USE')*RTBL7(R,SR,'CROPLAND','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOST','USE')*RTBL7(R,SR,'ACRCOST','PRICE')
                    + RTBL7(R,SR,'ACRECO','USE')*RTBL7(R,SR,'ACRECO','PRICE'));
RTBL20(SR,'LANDRENTP') =
    SUM(R $RSR(R,SR), RTBL7(R,SR,'PRMPAST','USE')*RTBL7(R,SR,'PRMPAST','PRICE')
                    + RTBL7(R,SR,'PRMPASTB','USE')*RTBL7(R,SR,'PRMPASTB','PRICE')
                    + RTBL7(R,SR,'PRMPASTT','USE')*RTBL7(R,SR,'PRMPASTT','PRICE')
                    + RTBL7(R,SR,'PRMPASTH','USE')*RTBL7(R,SR,'PRMPASTH','PRICE')
                    + RTBL7(R,SR,'PRMPASTN','USE')*RTBL7(R,SR,'PRMPASTN','PRICE')
                    + RTBL7(R,SR,'PRMPASTHB','USE')*RTBL7(R,SR,'PRMPASTHB','PRICE')
                    + RTBL7(R,SR,'PRMPASTHT','USE')*RTBL7(R,SR,'PRMPASTHT','PRICE')
                    + RTBL7(R,SR,'PRMPASTHN','USE')*RTBL7(R,SR,'PRMPASTHN','PRICE')
                    + RTBL7(R,SR,'PRMALV','USE')*RTBL7(R,SR,'PRMALV','PRICE')
                    + RTBL7(R,SR,'PRMFOR','USE')*RTBL7(R,SR,'PRMFOR','PRICE')
                    + RTBL7(R,SR,'PRMMOS','USE')*RTBL7(R,SR,'PRMMOS','PRICE')
                    + RTBL7(R,SR,'PRMLOW','USE')*RTBL7(R,SR,'PRMLOW','PRICE')
                    + RTBL7(R,SR,'PRMCHAL','USE')*RTBL7(R,SR,'PRMCHAL','PRICE')
                    + RTBL7(R,SR,'PRMMEAD','USE')*RTBL7(R,SR,'PRMMEAD','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTP','USE')*RTBL7(R,SR,'ACRCOSTP','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTPB','USE')*RTBL7(R,SR,'ACRCOSTPB','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTPT','USE')*RTBL7(R,SR,'ACRCOSTPT','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTPN','USE')*RTBL7(R,SR,'ACRCOSTPN','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTPH','USE')*RTBL7(R,SR,'ACRCOSTPH','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTPHB','USE')*RTBL7(R,SR,'ACRCOSTPHB','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTPHT','USE')*RTBL7(R,SR,'ACRCOSTPHT','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTPHN','USE')*RTBL7(R,SR,'ACRCOSTPHN','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTALV','USE')*RTBL7(R,SR,'ACRCOSTALV','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTFOR','USE')*RTBL7(R,SR,'ACRCOSTFOR','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTMOS','USE')*RTBL7(R,SR,'ACRCOSTMOS','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTLOW','USE')*RTBL7(R,SR,'ACRCOSTLOW','PRICE')
                    + 0.5*RTBL7(R,SR,'ACRCOSTCHA','USE')*RTBL7(R,SR,'ACRCOSTCHA','PRICE')                    
                    + 0.5*RTBL7(R,SR,'ACRCOSTMEA','USE')*RTBL7(R,SR,'ACRCOSTMEA','PRICE'));

RTBL20(SR,'PRODSURPL') = RTBL20(SR,'LANDRENTC') + RTBL20(SR,'LANDRENTP') 
   + SUM(R $RSR(R,SR), SUM(FIXIS, RTBL7(R,SR,FIXIS,'FIXED-SUP')*RTBL7(R,SR,FIXIS,'PRICE')))
   + SUM(R $RSR(R,SR), SUM(FIXIS2, RTBL7(R,SR,FIXIS2,'USE')*RTBL7(R,SR,FIXIS2,'PRICE')))/2
   + SUM(R $RSR(R,SR), SUM(AS $RSRAS(R,SR,AS),
                       +  EAS(R,SR,AS,'MEDCOW')*PRODSR.L(R,SR,AS)*RTBL8(R,'MEDCOW','PRICE')
                       +  EAS(R,SR,AS,'MEBEEFCATT')*PRODSR.L(R,SR,AS)*RTBL8(R,'MEBEEFCATT','PRICE')
                       +  EAS(R,SR,AS,'MESHEEP')*PRODSR.L(R,SR,AS)*RTBL8(R,'MESHEEP','PRICE')
                       +  EAS(R,SR,AS,'MECOPIG')*PRODSR.L(R,SR,AS)*RTBL8(R,'MECOPIG','PRICE')
                       +  EAS(R,SR,AS,'MEPOULTRY')*PRODSR.L(R,SR,AS)*RTBL8(R,'MEPOULTRY','PRICE'))); 

RTBL13E('LANDVCROP',SR)  = RTBL20(SR,'LANDRENTC')/SUM(R $RSR(R,SR), RTBL7(R,SR,'CROPLAND','USE'))*1000;

RTBL13E('LANDVPAST',SR)  = RTBL20(SR,'LANDRENTP')/SUM(R $RSR(R,SR), 
                              (RTBL7(R,SR,'PRMPAST','USE')+ RTBL7(R,SR,'PRMPASTB','USE')
                              +RTBL7(R,SR,'PRMPASTT','USE')+RTBL7(R,SR,'PRMPASTN','USE')
                              +RTBL7(R,SR,'PRMPASTH','USE')+RTBL7(R,SR,'PRMPASTHB','USE')
                              +RTBL7(R,SR,'PRMPASTHT','USE')+RTBL7(R,SR,'PRMPASTHN','USE')
                              +RTBL7(R,SR,'PRMALV','USE')+RTBL7(R,SR,'PRMFOR','USE')
                              +RTBL7(R,SR,'PRMMOS','USE')+RTBL7(R,SR,'PRMLOW','USE')
                              +RTBL7(R,SR,'PRMCHAL','USE')+RTBL7(R,SR,'PRMMEAD','USE')))*1000;
RTBL13E('PRODSURPL',SR)  = RTBL20(SR,'PRODSURPL');

RTBL13E('LANDVCROP','RIKET')= SUM(SR, RTBL20(SR,'LANDRENTC')) /
                                SUM(SR, SUM(R $RSR(R,SR), RTBL7(R,SR,'CROPLAND','USE')))*1000;
RTBL13E('LANDVPAST','RIKET')= SUM(SR, RTBL20(SR,'LANDRENTP')) / SUM(SR, SUM(R $RSR(R,SR),
                               RTBL7(R,SR,'PRMPAST','USE')+ RTBL7(R,SR,'PRMPASTB','USE')
                              +RTBL7(R,SR,'PRMPASTT','USE')+ RTBL7(R,SR,'PRMPASTN','USE')
                              +RTBL7(R,SR,'PRMPASTH','USE')+RTBL7(R,SR,'PRMPASTHB','USE')
                              +RTBL7(R,SR,'PRMPASTHT','USE')+RTBL7(R,SR,'PRMPASTHN','USE')
                              +RTBL7(R,SR,'PRMALV','USE')+RTBL7(R,SR,'PRMFOR','USE')
                              +RTBL7(R,SR,'PRMMOS','USE')+RTBL7(R,SR,'PRMLOW','USE')
                              +RTBL7(R,SR,'PRMCHAL','USE')+RTBL7(R,SR,'PRMMEAD','USE')))*1000;
RTBL13E('PRODSURPL','RIKET')= SUM(SR, RTBL13E('PRODSURPL',SR));


PARAMETER RTBL13E2(*,*)  Crop acreage and numbers of livestock by Output-region;
RTBL13E2('VALL',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('VALL',SR)); 
RTBL13E2('HOSTSAD',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('HOSTSAD',SR)); 
RTBL13E2('VARSAD',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('VARSAD',SR)); 
RTBL13E2('OLJEVAXT',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('OLJEVAXT',SR)); 
RTBL13E2('UTTAG',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('UTTAG',SR)); 
RTBL13E2('OVGRODOR',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('OVGRODOR',SR)); 
RTBL13E2('AKER',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('AKER',SR)); 
RTBL13E2('BETESMARK',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('BETESMARK',SR)); 
RTBL13E2('MJOLKKO',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('MJOLKKO',SR)); 
RTBL13E2('DIKO',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('DIKO',SR)); 
RTBL13E2('REKKVIGA1',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('REKKVIGA1',SR)); 
RTBL13E2('REKKVIGA2',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('REKKVIGA2',SR)); 
RTBL13E2('SLAKTKVIG1',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('SLAKTKVIG1',SR)); 
RTBL13E2('SLAKTKVIG2',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('SLAKTKVIG2',SR)); 
RTBL13E2('TJUR1',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('TJUR1',SR)); 
RTBL13E2('TJUR2',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('TJUR2',SR)); 
RTBL13E2('STUT1',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('STUT1',SR)); 
RTBL13E2('STUT2',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('STUT2',SR)); 
RTBL13E2('SUGGA',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('SUGGA',SR)); 
RTBL13E2('DIREKTBET',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('DIREKTBET',SR)); 
RTBL13E2('AE&DB',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('AE&DB',SR)); 
RTBL13E2('N-BOUGHT',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('N-BOUGHT',SR)); 
RTBL13E2('P-BOUGHT',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('P-BOUGHT',SR)); 
RTBL13E2('K-BOUGHT',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('K-BOUGHT',SR)); 
*RTBL13E2('LANDVCROP',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('LANDVCROP',SR)); 
*RTBL13E2('LANDVPAST',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('LANDVPAST',SR)); 
RTBL13E2('LANDVCROP',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL20(SR,'LANDRENTC')) / SUM(SR $UPRSR(UPR,SR),
                                 SUM(R $RSR(R,SR), RTBL7(R,SR,'CROPLAND','USE')))*1000; 
RTBL13E2('LANDVPAST',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL20(SR,'LANDRENTP')) / 
                              SUM(SR $UPRSR(UPR,SR), SUM(R $RSR(R,SR),
                               RTBL7(R,SR,'PRMPAST','USE')+ RTBL7(R,SR,'PRMPASTB','USE')
                              +RTBL7(R,SR,'PRMPASTT','USE')+RTBL7(R,SR,'PRMPASTN','USE')
                              +RTBL7(R,SR,'PRMPASTH','USE')+RTBL7(R,SR,'PRMPASTHB','USE')
                              +RTBL7(R,SR,'PRMPASTHT','USE')+RTBL7(R,SR,'PRMPASTHN','USE')
                              +RTBL7(R,SR,'PRMALV','USE')+RTBL7(R,SR,'PRMFOR','USE')
                              +RTBL7(R,SR,'PRMMOS','USE')+RTBL7(R,SR,'PRMLOW','USE')
                              +RTBL7(R,SR,'PRMCHAL','USE')+RTBL7(R,SR,'PRMMEAD','USE')))*1000; 
RTBL13E2('PRODSURPL',UPR) = SUM(SR $UPRSR(UPR,SR), RTBL13E('PRODSURPL',SR)); 
RTBL13E2('VALL','RIKET')= RTBL13E('VALL','RIKET');
RTBL13E2('HOSTSAD','RIKET')= RTBL13E('HOSTSAD','RIKET');
RTBL13E2('VARSAD','RIKET')= RTBL13E('VARSAD','RIKET');
RTBL13E2('OLJEVAXT','RIKET')= RTBL13E('OLJEVAXT','RIKET');
RTBL13E2('UTTAG','RIKET')= RTBL13E('UTTAG','RIKET');
RTBL13E2('OVGRODOR','RIKET')= RTBL13E('OVGRODOR','RIKET');
RTBL13E2('AKER','RIKET')= RTBL13E('AKER','RIKET');
RTBL13E2('BETESMARK','RIKET')= RTBL13E('BETESMARK','RIKET');
RTBL13E2('MJOLKKO','RIKET')= RTBL13E('MJOLKKO','RIKET');
RTBL13E2('DIKO','RIKET')= RTBL13E('DIKO','RIKET');
RTBL13E2('REKKVIGA1','RIKET')= RTBL13E('REKKVIGA1','RIKET');
RTBL13E2('REKKVIGA2','RIKET')= RTBL13E('REKKVIGA2','RIKET');
RTBL13E2('SLAKTKVIG1','RIKET')= RTBL13E('SLAKTKVIG1','RIKET');
RTBL13E2('SLAKTKVIG2','RIKET')= RTBL13E('SLAKTKVIG2','RIKET');
RTBL13E2('TJUR1','RIKET')= RTBL13E('TJUR1','RIKET');
RTBL13E2('TJUR2','RIKET')= RTBL13E('TJUR2','RIKET');
RTBL13E2('STUT1','RIKET')= RTBL13E('STUT1','RIKET');
RTBL13E2('STUT2','RIKET')= RTBL13E('STUT2','RIKET');
RTBL13E2('SUGGA','RIKET')= RTBL13E('SUGGA','RIKET');
RTBL13E2('DIREKTBET','RIKET')= RTBL13E('DIREKTBET','RIKET');
RTBL13E2('AE&DB','RIKET')= RTBL13E('AE&DB','RIKET');
RTBL13E2('N-BOUGHT','RIKET')= RTBL13E('N-BOUGHT','RIKET');
RTBL13E2('P-BOUGHT','RIKET')= RTBL13E('P-BOUGHT','RIKET');
RTBL13E2('K-BOUGHT','RIKET')= RTBL13E('K-BOUGHT','RIKET');
RTBL13E2('LANDVCROP','RIKET')= RTBL13E('LANDVCROP','RIKET');
RTBL13E2('LANDVPAST','RIKET')= RTBL13E('LANDVPAST','RIKET');
RTBL13E2('PRODSURPL','RIKET')= RTBL13E('PRODSURPL','RIKET');


PARAMETER RTBL21(SR,*)  Miscellaneous pasture data by production region;

RTBL21(SR,'LVSTCAP')  = SUM(R $RSR(R,SR), RTBL1(R,SR,'USEPASTR','PRODUCTION'));
RTBL21(SR,'LVSTUSED') = SUM(R $RSR(R,SR), RTBL1(R,SR,'USEPASTR','USE'));
RTBL21(SR,'PASTGRUSED') = SUM(R $RSR(R,SR), RTBL1(R,SR,'GRASSPASTR','USE'));
RTBL21(SR,'UNNESSFOR')= SUM(R $RSR(R,SR), RTBL1(R,SR,'GRASSPASTF','PRODUCTION')-RTBL1(R,SR,'GRASSPASTF','USE'));
RTBL21(SR,'LVSTTRPT') = RTBL13B(SR,'LVSTKIN')-RTBL13B(SR,'LVSTKOUT');
RTBL21(SR,'PRICEPAST')= SUM(R $RSR(R,SR), RTBL1(R,SR,'GRASSPASTR','PRICE')-RTBL1(R,SR,'USEPASTR','PRICE'));
RTBL21(SR,'PRICEPASTF')=SUM(R $RSR(R,SR), RTBL1(R,SR,'GRASSPASTR','PRICE')+RTBL1(R,SR,'GRASSPASTF','PRICE'));
RTBL21(SR,'PASTUSED') = SUM(R $RSR(R,SR), RTBL7(R,SR,'PRMPAST','USE')+RTBL7(R,SR,'PRMPASTT','USE')
       + RTBL7(R,SR,'PRMPASTN','USE')+RTBL7(R,SR,'PRMPASTH','USE')+RTBL7(R,SR,'PRMPASTHT','USE')
       + RTBL7(R,SR,'PRMPASTHN','USE')+RTBL7(R,SR,'PRMALV','USE')+RTBL7(R,SR,'PRMFOR','USE')
       + RTBL7(R,SR,'PRMMOS','USE')+RTBL7(R,SR,'PRMLOW','USE')+RTBL7(R,SR,'PRMCHAL','USE')
       + RTBL7(R,SR,'PRMMEAD','USE')-RTBL7(R,SR,'PRMPAST','PRODUCTION')-RTBL7(R,SR,'PRMPASTT','PRODUCTION')
       - RTBL7(R,SR,'PRMPASTN','PRODUCTION')-RTBL7(R,SR,'PRMPASTH','PRODUCTION')-RTBL7(R,SR,'PRMPASTHT','PRODUCTION')
       - RTBL7(R,SR,'PRMPASTHN','PRODUCTION')-RTBL7(R,SR,'PRMALV','PRODUCTION')-RTBL7(R,SR,'PRMFOR','PRODUCTION')
       - RTBL7(R,SR,'PRMMOS','PRODUCTION')-RTBL7(R,SR,'PRMLOW','PRODUCTION')-RTBL7(R,SR,'PRMCHAL','PRODUCTION')
       - RTBL7(R,SR,'PRMMEAD','PRODUCTION'));
RTBL21(SR,'PASTAVAIL')= SUM(R $RSR(R,SR), RTBL7(R,SR,'PRMPAST','FIXED-SUP')+RTBL7(R,SR,'PRMPASTT','FIXED-SUP')
       + RTBL7(R,SR,'PRMPASTN','FIXED-SUP')+RTBL7(R,SR,'PRMPASTH','FIXED-SUP')+RTBL7(R,SR,'PRMPASTHT','FIXED-SUP')
       + RTBL7(R,SR,'PRMPASTHN','FIXED-SUP')+RTBL7(R,SR,'PRMALV','FIXED-SUP')+RTBL7(R,SR,'PRMFOR','FIXED-SUP')
       + RTBL7(R,SR,'PRMMOS','FIXED-SUP')+RTBL7(R,SR,'PRMLOW','FIXED-SUP')+RTBL7(R,SR,'PRMCHAL','FIXED-SUP')
       + RTBL7(R,SR,'PRMMEAD','FIXED-SUP'));
RTBL21(SR,'PASTPOT')  = RTBL21(SR,'PASTAVAIL') - RTBL21(SR,'PASTUSED');       

PARAMETER RTBL0(*,*)  Calculated surpluses;


*RTBL0(R,'PRODSUR') = SUM(PR $PRED(R,PR), (PRODUCTRE.M(R,PR)*(-DEMANDPR.L(R,PR))))
*         + SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (PRODUCTSE.M(R,SR,PS)*(-DEMANDPS.L(R,SR,PS)))))
*         - SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
*                               *(SUPPLYIR.L(R,IR)**2)))
*         - SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
*                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2))));
RTBL0(R,'PRODSUR') =
          SUM(PR $PRED(R,PR), (-PRODUCTRE.M(R,PR) *
                                           (RTBL2(R,PR,'PRODUCTION')- RTBL2(R,PR,'USE'))))
         + SUM(PR $PRFD(R,PR), (-PRODUCTRF.M(R,PR) *
                                           (RTBL2(R,PR,'PRODUCTION')- RTBL2(R,PR,'USE'))))
         + SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (-PRODUCTSE.M(R,SR,PS) *
                                           (RTBL1(R,SR,PS,'PRODUCTION')- RTBL1(R,SR,PS,'USE')))))
         + SUM(PN $PNED(PN), -PRODUCTNE.M(PN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               - EAS(R,SR,AS,PN)*PRODSR.L(R,SR,AS)))
                               + SUM(CR $(RCR(R,CR)), -ECR(R,CR,PN)*PROCR.L(R,CR))))       
         - SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)))
         - SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2))))
         - SUM(IN $INES(IN), (BIN(IN,'INTERCEPT') * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               + EAS(R,SR,AS,IN)*PRODSR.L(R,SR,AS)))
                               + SUM(CR $(RCR(R,CR)), +ECR(R,CR,IN)*PROCR.L(R,CR)))));
RTBL0(R,'PSURI') =
          SUM(PR $PRED(R,PR), (-PRODUCTRE.M(R,PR) *
                                           (RTBL2(R,PR,'PRODUCTION')- RTBL2(R,PR,'USE'))))
         + SUM(PR $PRFD(R,PR),(-PRODUCTRF.M(R,PR) *
                                           (RTBL2(R,PR,'PRODUCTION')- RTBL2(R,PR,'USE')))) 
         + SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (-PRODUCTSE.M(R,SR,PS) *
                                           (RTBL1(R,SR,PS,'PRODUCTION')- RTBL1(R,SR,PS,'USE')))))
         + SUM(PN $PNED(PN), -PRODUCTNE.M(PN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               - EAS(R,SR,AS,PN)*PRODSR.L(R,SR,AS)))
         + SUM(CR $(RCR(R,CR)), -ECR(R,CR,PN)*PROCR.L(R,CR))));
RTBL0(R,'PSURIN') =
         + SUM(PN $PNED(PN), -PRODUCTNE.M(PN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               -EAS(R,SR,AS,PN)*PRODSR.L(R,SR,AS)))
         + SUM(CR $(RCR(R,CR)), -ECR(R,CR,PN)*PROCR.L(R,CR))));         
RTBL0(R,'PSURIR') =
          SUM(PR $PRED(R,PR),(-PRODUCTRE.M(R,PR) *
                (RTBL2(R,PR,'PRODUCTION')- RTBL2(R,PR,'USE'))))
         +SUM(PR $PRFD(R,PR),(-PRODUCTRF.M(R,PR) *
                (RTBL2(R,PR,'PRODUCTION')- RTBL2(R,PR,'USE')))); 
RTBL0(R,'PSURIS') =
         + SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (-PRODUCTSE.M(R,SR,PS) *
                                           (RTBL1(R,SR,PS,'PRODUCTION')- RTBL1(R,SR,PS,'USE')))));
RTBL0(R,'PSURC') =
         - SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)))
         - SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2))))
         - SUM(IN $INES(IN), INPUTNE.M(IN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               + EAS(R,SR,AS,IN)*PRODSR.L(R,SR,AS)))
                               + SUM(CR $(RCR(R,CR)), +ECR(R,CR,IN)*PROCR.L(R,CR))));
RTBL0(R,'PSURCN') = SUM(IN $INES(IN), INPUTNE.M(IN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               - EAS(R,SR,AS,IN)*PRODSR.L(R,SR,AS)))
                               + SUM(CR $(RCR(R,CR)), -ECR(R,CR,IN)*PROCR.L(R,CR)))); 
RTBL0(R,'PSURCN1') = SUM(IN $INES(IN), INPUTNE.M(IN) * SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               - EAS(R,SR,AS,IN)*PRODSR.L(R,SR,AS))));
RTBL0(R,'PSURCN2') = SUM(IN $INES(IN), INPUTNE.M(IN) * 
                               SUM(CR $(RCR(R,CR)), -ECR(R,CR,IN)*PROCR.L(R,CR))); 
RTBL0(R,'PSURCR') =
         - SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)));
RTBL0(R,'PSURCS') =
         - SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2))));


RTBL0(R,'CONSSUR') =  + SUM(PR $PRED(R,PR), (BPR(R,PR,'INTERCEPT')*DEMANDPR.L(R,PR))+(0.5*BPR(R,PR,'SLOPE')
                              *(DEMANDPR.L(R,PR)**2))-(PRODUCTRE.M(R,PR)*(-DEMANDPR.L(R,PR))))
    + SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (BPS(R,SR,PS,'INTERCEPT')*DEMANDPS.L(R,SR,PS))
       +(0.5*BPS(R,SR,PS,'SLOPE')*(DEMANDPS.L(R,SR,PS)**2))-(PRODUCTSE.M(R,SR,PS)*(-DEMANDPS.L(R,SR,PS)))));

RTBL0(R,'VALFIXSUP') =  + SUM(IR $IRFS(R,IR), -(INPUTRF.M(R,IR)*BIR(R,IR,'MAX')))
           + SUM(SR $RSR(R,SR), SUM(IS $ISFS(R,SR,IS), -(INPUTSF.M(R,SR,IS)*BIS(R,SR,IS,'MAX'))))
           + SUM(IN $INFS(IN), -INPUTNF.M(IN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                          - EAS(R,SR,AS,IN)*PRODSR.L(R,SR,AS)))
                          + SUM(CR $(RCR(R,CR)), -ECR(R,CR,IN)*PROCR.L(R,CR))));
RTBL0(R,'VALFIXSUPS') =  
           + SUM(SR $RSR(R,SR), SUM(IS $ISFS(R,SR,IS), -(INPUTSF.M(R,SR,IS)*BIS(R,SR,IS,'MAX'))));
RTBL0(R,'VALFIXSUPR') =  + SUM(IR $IRFS(R,IR), -(INPUTRF.M(R,IR)*BIR(R,IR,'MAX')));
           
RTBL0(R,'VALFIXSUPN') =  SUM(IN $INFS(IN), -INPUTNF.M(IN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                          - EAS(R,SR,AS,IN)*PRODSR.L(R,SR,AS)))
                          + SUM(CR $(RCR(R,CR)), -ECR(R,CR,IN)*PROCR.L(R,CR))));

RTBL0(R,'COSTFIXDEM') =  + SUM(PR $PRFD(R,PR), -(PRODUCTRF.M(R,PR)*(PRODUCTRF.LO(R,PR))))
           + SUM(SR $RSR(R,SR), SUM(PS $PSFD(R,SR,PS), -(PRODUCTSF.M(R,SR,PS)*(PRODUCTSF.LO(R,SR,PS)))))
           + SUM(PN, -PRODUCTNF.M(PN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                          - EAS(R,SR,AS,PN)*PRODSR.L(R,SR,AS)))
                          + SUM(CR $(RCR(R,CR)), -ECR(R,CR,PN)*PROCR.L(R,CR))));
RTBL0(R,'CFIXDEMS') =  
           + SUM(SR $RSR(R,SR), SUM(PS $PSFD(R,SR,PS), -(PRODUCTSF.M(R,SR,PS)*(PRODUCTSF.LO(R,SR,PS)))));
RTBL0(R,'CFIXDEMR') =  SUM(PR $PRFD(R,PR), -(PRODUCTRF.M(R,PR)*(PRODUCTRF.LO(R,PR))));
RTBL0(R,'CFIXDEMN') =  SUM(PN, -PRODUCTNF.M(PN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                          - EAS(R,SR,AS,PN)*PRODSR.L(R,SR,AS)))
                          + SUM(CR $(RCR(R,CR)), -ECR(R,CR,PN)*PROCR.L(R,CR))));
RTBL0(RD,'TRANCOST') = SUM(RS, SUM(IP $TIP(RS,RD,IP), CT(RS,RD,IP)*TRANIP.L(RS,RD,IP)));
RTBL0(RD,'TRANCOSTP') = SUM(RS, SUM(PR $TIP(RS,RD,PR), CT(RS,RD,PR)*TRANIP.L(RS,RD,PR)));
rTBL0(RD,'TRANCOSTI') = SUM(RS, SUM(IR $TIP(RS,RD,IR), CT(RS,RD,IR)*TRANIP.L(RS,RD,IR)));

RTBL0(R,'EXPREV1') = SUM(PREX $RPREX(R,PREX), BXR(R,PREX,'ADJPRICE')*EXPORTRP.L(R,PREX));
RTBL0(R,'EXPREV2') = SUM(PREX $RPREX(R,PREX), -(PRODUCTRE.M(R,PREX)+PRODUCTRF.M(R,PREX))*EXPORTRP.L(R,PREX));
RTBL0(R,'EXPREV3') =  RTBL0(R,'EXPREV2') - RTBL0(R,'EXPREV1');
RTBL0(R,'IMPCOST1') =  SUM(PRIM $RPRIM(R,PRIM), BMR(R,PRIM,'ADJPRICE')*IMPORTPR.L(R,PRIM));
RTBL0(R,'IMPCOST2') =  SUM(PRIM $RPRIM(R,PRIM), -(PRODUCTRE.M(R,PRIM)+PRODUCTRF.M(R,PRIM))*IMPORTPR.L(R,PRIM));
RTBL0(R,'IMPCOST3') =  RTBL0(R,'IMPCOST2') - RTBL0(R,'IMPCOST1');

RTBL0(R,'OBJECTIV') =  RTBL0(R,'CONSSUR') + RTBL0(R,'PRODSUR'); 
RTBL0(R,'OBJ') = 
  - SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)))
         - SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2))))
  + SUM(PR $PRED(R,PR), (BPR(R,PR,'INTERCEPT')*DEMANDPR.L(R,PR))+(0.5*BPR(R,PR,'SLOPE')
                              *(DEMANDPR.L(R,PR)**2)))
+ SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (BPS(R,SR,PS,'INTERCEPT')*DEMANDPS.L(R,SR,PS))
                                  +(0.5*BPS(R,SR,PS,'SLOPE')*(DEMANDPS.L(R,SR,PS)**2))))
  - SUM(RS, SUM(IP $TIP(RS,R,IP), CT(RS,R,IP)*TRANIP.L(RS,R,IP)))
  + SUM(IN $INES(IN), INPUTNE.M(IN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               - EAS(R,SR,AS,IN)*PRODSR.L(R,SR,AS)))
                               + SUM(CR $(RCR(R,CR)), -ECR(R,CR,IN)*PROCR.L(R,CR))))
  + SUM(PN $PNED(PN), -PRODUCTNE.M(PN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               -EAS(R,SR,AS,PN)*PRODSR.L(R,SR,AS)))
         + SUM(CR $(RCR(R,CR)), -ECR(R,CR,PN)*PROCR.L(R,CR))))
  + SUM(PREX $RPREX(R,PREX), BXR(R,PREX,'ADJPRICE')*EXPORTRP.L(R,PREX))
  - SUM(PRIM $RPRIM(R,PRIM), BMR(R,PRIM,'ADJPRICE')*IMPORTPR.L(R,PRIM));

RTBL0(R,'OBJC') = 
  - SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)))
         - SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2))));
RTBL0(R,'OBJI') = 
  + SUM(PR $PRED(R,PR), (BPR(R,PR,'INTERCEPT')*DEMANDPR.L(R,PR))+(0.5*BPR(R,PR,'SLOPE')
                              *(DEMANDPR.L(R,PR)**2)))
+ SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (BPS(R,SR,PS,'INTERCEPT')*DEMANDPS.L(R,SR,PS))
                                  +(0.5*BPS(R,SR,PS,'SLOPE')*(DEMANDPS.L(R,SR,PS)**2))));


RTBL0(R,'OBJ1') = - SUM(RS, SUM(IP $TIP(RS,R,IP), CT(RS,R,IP)*TRANIP.L(RS,R,IP)));
RTBL0(R,'OBJ2') = + SUM(IN $INES(IN), INPUTNE.M(IN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               - EAS(R,SR,AS,IN)*PRODSR.L(R,SR,AS)))
                               + SUM(CR $(RCR(R,CR)), -ECR(R,CR,IN)*PROCR.L(R,CR))));
RTBL0(R,'OBJ3') = + SUM(PN $PNED(PN), -PRODUCTNE.M(PN) * (SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                               -EAS(R,SR,AS,PN)*PRODSR.L(R,SR,AS)))
         + SUM(CR $(RCR(R,CR)), -ECR(R,CR,PN)*PROCR.L(R,CR))));
RTBL0(R,'OBJEXP') =  + SUM(PREX $RPREX(R,PREX), BXR(R,PREX,'ADJPRICE')*EXPORTRP.L(R,PREX));
RTBL0(R,'OBJIMP') =  - SUM(PRIM $RPRIM(R,PRIM), BMR(R,PRIM,'ADJPRICE')*IMPORTPR.L(R,PRIM));
RTBL0(R,'OBJTROUT') = - SUM(RD, SUM(PR $TIP(R,RD,PR), PRODUCTRE.M(R,PR)*TRANIP.L(R,RD,PR)));
RTBL0(R,'OBJTRIN') =  + SUM(RS, SUM(PR $TIP(RS,R,PR), PRODUCTRE.M(R,PR)*TRANIP.L(RS,R,PR)));

RTBL0('SWEDEN','PRODSUR') =  SUM(R, RTBL0(R,'PRODSUR'));
RTBL0('SWEDEN','PSURI') =  SUM(R, RTBL0(R,'PSURI'));
RTBL0('SWEDEN','PSURIN') =  SUM(R, RTBL0(R,'PSURIN'));                           
RTBL0('SWEDEN','PSURIR') =  SUM(R, RTBL0(R,'PSURIR'));
RTBL0('SWEDEN','PSURIS') =  SUM(R, RTBL0(R,'PSURIS'));
RTBL0('SWEDEN','PSURC') =  SUM(R, RTBL0(R,'PSURC'));
RTBL0('SWEDEN','PSURCN') =  SUM(R, RTBL0(R,'PSURCN'));
RTBL0('SWEDEN','PSURCN1') =  SUM(R, RTBL0(R,'PSURCN1'));
RTBL0('SWEDEN','PSURCN2') =  SUM(R, RTBL0(R,'PSURCN2'));
RTBL0('SWEDEN','PSURCR') =  SUM(R, RTBL0(R,'PSURCR'));
RTBL0('SWEDEN','PSURCS') =  SUM(R, RTBL0(R,'PSURCS'));
RTBL0('SWEDEN','CONSSUR') =  SUM(R, RTBL0(R,'CONSSUR'));
RTBL0('SWEDEN','VALFIXSUP') =  SUM(R, RTBL0(R,'VALFIXSUP'));
RTBL0('SWEDEN','VALFIXSUPS') =  SUM(R, RTBL0(R,'VALFIXSUPS'));
RTBL0('SWEDEN','VALFIXSUPR') =  SUM(R, RTBL0(R,'VALFIXSUPR'));
RTBL0('SWEDEN','VALFIXSUPN') =  SUM(R, RTBL0(R,'VALFIXSUPN'));
RTBL0('SWEDEN','COSTFIXDEM') =  SUM(R, RTBL0(R,'COSTFIXDEM'));
RTBL0('SWEDEN','CFIXDEMS') =  SUM(R, RTBL0(R,'CFIXDEMS'));
RTBL0('SWEDEN','CFIXDEMR') =  SUM(R, RTBL0(R,'CFIXDEMR'));
RTBL0('SWEDEN','CFIXDEMN') =  SUM(R, RTBL0(R,'CFIXDEMN'));
RTBL0('SWEDEN','TRANCOST') =  SUM(R, RTBL0(R,'TRANCOST'));
RTBL0('SWEDEN','EXPREV1') =  SUM(R, RTBL0(R,'EXPREV1'));
RTBL0('SWEDEN','EXPREV2') =  SUM(R, RTBL0(R,'EXPREV2'));
RTBL0('SWEDEN','EXPREV3') =  SUM(R, RTBL0(R,'EXPREV3'));
RTBL0('SWEDEN','IMPCOST1') =  SUM(R, RTBL0(R,'IMPCOST1'));
RTBL0('SWEDEN','IMPCOST2') =  SUM(R, RTBL0(R,'IMPCOST2'));
RTBL0('SWEDEN','IMPCOST3') =  SUM(R, RTBL0(R,'IMPCOST3'));
RTBL0('SWEDEN','OBJECTIV') =  SUM(R, RTBL0(R,'OBJECTIV'));
RTBL0('SWEDEN','OBJ') =  SUM(R, RTBL0(R,'OBJ'));
RTBL0('SWEDEN','OBJC') =  SUM(R, RTBL0(R,'OBJC'));
RTBL0('SWEDEN','OBJI') =  SUM(R, RTBL0(R,'OBJI'));
RTBL0('SWEDEN','OBJ1') =  SUM(R, RTBL0(R,'OBJ1'));
RTBL0('SWEDEN','OBJ2') =  SUM(R, RTBL0(R,'OBJ2'));
RTBL0('SWEDEN','OBJ3') =  SUM(R, RTBL0(R,'OBJ3'));
RTBL0('SWEDEN','OBJEXP') =  SUM(R, RTBL0(R,'OBJEXP'));
RTBL0('SWEDEN','OBJIMP') =  SUM(R, RTBL0(R,'OBJIMP'));
RTBL0('SWEDEN','OBJTROUT') =  SUM(R, RTBL0(R,'OBJTROUT'));
RTBL0('SWEDEN','OBJTRIN') =  SUM(R, RTBL0(R,'OBJTRIN'));



PARAMETER RTBL0B(*,*)  Calculated aggragated surpluses;

RTBL0B(R,'PRODSURP') = RTBL0(R,'PRODSUR') + RTBL0(R,'COSTFIXDEM');
RTBL0B(R,'CONSSURP') = RTBL0(R,'CONSSUR') - RTBL0(R,'COSTFIXDEM');
RTBL0B(R,'TAXPAYER') = SUM(SR $RSR(R,SR), RTBL13E('DIREKTBET',SR));
RTBL0B(R,'WELFARE')  = RTBL0B(R,'PRODSURP') + RTBL0B(R,'CONSSURP')-RTBL0B(R,'TAXPAYER');
RTBL0B(R,'OBJFCN')   = RTBL0B(R,'PRODSURP') + RTBL0B(R,'CONSSURP');

RTBL0B('SWEDEN','PRODSURP') =  SUM(R, RTBL0B(R,'PRODSURP'));
RTBL0B('SWEDEN','CONSSURP') =  SUM(R, RTBL0B(R,'CONSSURP'));
RTBL0B('SWEDEN','TAXPAYER') =  SUM(R, RTBL0B(R,'TAXPAYER'));
RTBL0B('SWEDEN','WELFARE') =  SUM(R, RTBL0B(R,'WELFARE'));
RTBL0B('SWEDEN','OBJFCN') =  SUM(R, RTBL0B(R,'OBJFCN'));
RTBL0B('SWEDEN','DIFFOBJF') = RTBL0B('SWEDEN','OBJFCN') - Z.L;

PARAMETER RTBL0C(*,*) Value of national fixed inputs;
RTBL0C(INFS,R) = - SUM(SR $RSR(R,SR), SUM(AS $(RSRAS(R,SR,AS)),
                          - EAS(R,SR,AS,INFS)*PRODSR.L(R,SR,AS))
                          + SUM(CR $(RCR(R,CR)), -ECR(R,CR,INFS)*PROCR.L(R,CR)) * INPUTNF.M(INFS));


PARAMETER RTBL0A(*)  Calculated surpluses;

RTBL0A('PRODSUR') = 0;
RTBL0A('PRODSUR') = - SUM(R,
 -SUM(PR $PRED(R,PR), (PRODUCTRE.M(R,PR)*(-DEMANDPR.L(R,PR))))
         - SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (PRODUCTSE.M(R,SR,PS)*(-DEMANDPS.L(R,SR,PS)))))  
         + SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)))
         + SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2)))));
RTBL0A('PRODSUR1') = 0;
RTBL0A('PRODSUR1') = - SUM(R,  
         + SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)))
         + SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2)))));
RTBL0A('OBJ1P') = 0;
RTBL0A('OBJ1P') = 
  - SUM(R, SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)))
         + SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2)))));

RTBL0A('PRODSUR2') = 0;
RTBL0A('PRODSUR2') = SUM(R, SUM(PR $PRED(R,PR), (PRODUCTRE.M(R,PR)*(-DEMANDPR.L(R,PR))))
         + SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (PRODUCTSE.M(R,SR,PS)*(-DEMANDPS.L(R,SR,PS))))));                                  
RTBL0A('PRODSUR2S') = SUM(R, 
         + SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (PRODUCTSE.M(R,SR,PS)*(-DEMANDPS.L(R,SR,PS))))));
RTBL0A('PRODSUR2R') = SUM(R, SUM(PR $PRED(R,PR), (PRODUCTRE.M(R,PR)*(-DEMANDPR.L(R,PR)))));
*RTBL0A('PRODSUR2R') = SUM(R, (PRODUCTRE.M(R,'BEEF')*(-DEMANDPR.L(R,'BEEF'))));
*RTBL0A('PRODSUR2R') = (PRODUCTRE.M('R6','BREADGRAIN')*(-DEMANDPR.L('R6','BREADGRAIN')));

RTBL0A('CONSSUR') = 0;
RTBL0A('CONSSUR') =  + SUM(R, SUM(PR $PRED(R,PR), (BPR(R,PR,'INTERCEPT')*DEMANDPR.L(R,PR))+(0.5*BPR(R,PR,'SLOPE')
                              *(DEMANDPR.L(R,PR)**2))-(PRODUCTRE.M(R,PR)*(-DEMANDPR.L(R,PR))))
+ SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (BPS(R,SR,PS,'INTERCEPT')*DEMANDPS.L(R,SR,PS))
       +(0.5*BPS(R,SR,PS,'SLOPE')*(DEMANDPS.L(R,SR,PS)**2))-(PRODUCTSE.M(R,SR,PS)*(-DEMANDPS.L(R,SR,PS))))));
RTBL0A('CONSSUR1') = 0;
RTBL0A('CONSSUR1') =  + SUM(R, SUM(PR $PRED(R,PR), (BPR(R,PR,'INTERCEPT')*DEMANDPR.L(R,PR))+(0.5*BPR(R,PR,'SLOPE')
                              *(DEMANDPR.L(R,PR)**2)))
+ SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (BPS(R,SR,PS,'INTERCEPT')*DEMANDPS.L(R,SR,PS))
       +(0.5*BPS(R,SR,PS,'SLOPE')*(DEMANDPS.L(R,SR,PS)**2)))));
RTBL0A('CONSSUR2') = 0;
RTBL0A('CONSSUR2') =  + SUM(R, SUM(PR $PRED(R,PR), -(PRODUCTRE.M(R,PR)*(-DEMANDPR.L(R,PR))))
+ SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), -(PRODUCTSE.M(R,SR,PS)*(-DEMANDPS.L(R,SR,PS))))));

RTBL0A('TRANCOST') = 0;
RTBL0A('TRANCOST') = SUM(RD, SUM(RS, SUM(IP $TIP(RS,RD,IP), CT(RS,RD,IP)*TRANIP.L(RS,RD,IP))));

RTBL0A('EXPREV') = 0;
RTBL0A('EXPREV') = SUM(R, SUM(PREX $RPREX(R,PREX), BXR(R,PREX,'ADJPRICE')*EXPORTRP.L(R,PREX)));

RTBL0A('IMPCOST') = 0;
RTBL0A('IMPCOST') =  SUM(R, SUM(PRIM $RPRIM(R,PRIM), BMR(R,PRIM,'ADJPRICE')*IMPORTPR.L(R,PRIM)));

RTBL0A('PRODSURN') = 0;
RTBL0A('PRODSURN') = SUM(PN $PNED(PN), PRODUCTNE.M(PN)*(-DEMANDPN.L(PN)))
                - SUM(IN $INES(IN), (BIN(IN,'INTERCEPT')*SUPPLYIN.L(IN))+(0.5*BIN(IN,'SLOPE')*(SUPPLYIN.L(IN)**2)));
RTBL0A('CONSSURN') = 0;
RTBL0A('CONSSURN') =  + SUM(PN $PNED(PN), (BPN(PN,'INTERCEPT')*DEMANDPN.L(PN))
                          +(0.5*BPN(PN,'SLOPE')*(DEMANDPN.L(PN)**2)) -(PRODUCTNE.M(PN)*(-DEMANDPN.L(PN))));
RTBL0A('CSURN') = 0;
RTBL0A('CSURN') =  + SUM(PN $PNED(PN), (BPN(PN,'INTERCEPT')*DEMANDPN.L(PN))
                          +(0.5*BPN(PN,'SLOPE')*(DEMANDPN.L(PN)**2)));
RTBL0A('PSURN') = 0;
RTBL0A('PSURN') = SUM(PN $PNED(PN), PRODUCTNE.M(PN)*(-DEMANDPN.L(PN)));
RTBL0A('PSURCOSTN') = 0;
RTBL0A('PSURCOSTN') = - SUM(IN $INES(IN), (BIN(IN,'INTERCEPT')*SUPPLYIN.L(IN))
                             +(0.5*BIN(IN,'SLOPE')*(SUPPLYIN.L(IN)**2)));
RTBL0A('OBJ') = 0;
RTBL0A('OBJ') = 
  - SUM(R, SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)))
         + SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2)))))
  + SUM(R, SUM(PR $PRED(R,PR), (BPR(R,PR,'INTERCEPT')*DEMANDPR.L(R,PR))+(0.5*BPR(R,PR,'SLOPE')
                              *(DEMANDPR.L(R,PR)**2)))
+ SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (BPS(R,SR,PS,'INTERCEPT')*DEMANDPS.L(R,SR,PS))
                                  +(0.5*BPS(R,SR,PS,'SLOPE')*(DEMANDPS.L(R,SR,PS)**2)))))
  - SUM(RS, SUM(RD, SUM(IP $TIP(RS,RD,IP), CT(RS,RD,IP)*TRANIP.L(RS,RD,IP))))
  - SUM(IN $INES(IN), (BIN(IN,'INTERCEPT')*SUPPLYIN.L(IN))+(0.5*BIN(IN,'SLOPE')*(SUPPLYIN.L(IN)**2)))
  + SUM(PN $PNED(PN), (BPN(PN,'INTERCEPT')*DEMANDPN.L(PN))+(0.5*BPN(PN,'SLOPE')*(DEMANDPN.L(PN)**2)))
  + SUM(R, SUM(PREX $RPREX(R,PREX), BXR(R,PREX,'ADJPRICE')*EXPORTRP.L(R,PREX)))
  - SUM(R, SUM(PRIM $RPRIM(R,PRIM), BMR(R,PRIM,'ADJPRICE')*IMPORTPR.L(R,PRIM)));

RTBL0A('OBJ1') = 0;
RTBL0A('OBJ1') = 
  - SUM(R, SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)))
         + SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2)))))
  + SUM(R, SUM(PR $PRED(R,PR), (BPR(R,PR,'INTERCEPT')*DEMANDPR.L(R,PR))+(0.5*BPR(R,PR,'SLOPE')
                              *(DEMANDPR.L(R,PR)**2)))
+ SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (BPS(R,SR,PS,'INTERCEPT')*DEMANDPS.L(R,SR,PS))
                                  +(0.5*BPS(R,SR,PS,'SLOPE')*(DEMANDPS.L(R,SR,PS)**2)))));
RTBL0A('OBJ1P') = 
  - SUM(R, SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2)))
         + SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2)))));
RTBL0A('PSURCR') = 
  - SUM(R, SUM(IR $IRES(R,IR), (BIR(R,IR,'INTERCEPT')*SUPPLYIR.L(R,IR))+(0.5*BIR(R,IR,'SLOPE')
                               *(SUPPLYIR.L(R,IR)**2))));
RTBL0A('PSURCS') = 
  - SUM(R, SUM(SR $RSR(R,SR), SUM(IS $ISES(R,SR,IS), (BIS(R,SR,IS,'INTERCEPT')*SUPPLYIS.L(R,SR,IS))
                                  +(0.5*BIS(R,SR,IS,'SLOPE')*(SUPPLYIS.L(R,SR,IS)**2)))));
RTBL0A('PSURCN') = - SUM(IN $INES(IN),
                 (BIN(IN,'INTERCEPT')*SUPPLYIN.L(IN))+(0.5*BIN(IN,'SLOPE')*(SUPPLYIN.L(IN)**2)));
RTBL0A('OBJ1C') = 0;
RTBL0A('OBJ1C') = 
    + SUM(R, SUM(PR $PRED(R,PR), (BPR(R,PR,'INTERCEPT')*DEMANDPR.L(R,PR))+(0.5*BPR(R,PR,'SLOPE')
                              *(DEMANDPR.L(R,PR)**2)))
+ SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (BPS(R,SR,PS,'INTERCEPT')*DEMANDPS.L(R,SR,PS))
                                  +(0.5*BPS(R,SR,PS,'SLOPE')*(DEMANDPS.L(R,SR,PS)**2)))));
RTBL0A('PSURIRX') = 
    + SUM(R, SUM(PR $PRED(R,PR), (BPR(R,PR,'INTERCEPT')*DEMANDPR.L(R,PR))+(0.5*BPR(R,PR,'SLOPE')
                              *(DEMANDPR.L(R,PR)**2))));
RTBL0A('PSURISX') = 
    + SUM(R, SUM(SR $RSR(R,SR), SUM(PS $PSED(R,SR,PS), (BPS(R,SR,PS,'INTERCEPT')*DEMANDPS.L(R,SR,PS))
                                  +(0.5*BPS(R,SR,PS,'SLOPE')*(DEMANDPS.L(R,SR,PS)**2)))));
RTBL0A('PSURINX') = SUM(PN $PNED(PN),
                     (BPN(PN,'INTERCEPT')*DEMANDPN.L(PN))+(0.5*BPN(PN,'SLOPE')*(DEMANDPN.L(PN)**2)));
RTBL0A('OBJ2') = 0;
RTBL0A('OBJ2') = 
    - SUM(RS, SUM(RD, SUM(IP $TIP(RS,RD,IP), CT(RS,RD,IP)*TRANIP.L(RS,RD,IP))))
  - SUM(IN $INES(IN), (BIN(IN,'INTERCEPT')*SUPPLYIN.L(IN))+(0.5*BIN(IN,'SLOPE')*(SUPPLYIN.L(IN)**2)))
  + SUM(PN $PNED(PN), (BPN(PN,'INTERCEPT')*DEMANDPN.L(PN))+(0.5*BPN(PN,'SLOPE')*(DEMANDPN.L(PN)**2)))
  + SUM(R, SUM(PREX $RPREX(R,PREX), BXR(R,PREX,'ADJPRICE')*EXPORTRP.L(R,PREX)))
  - SUM(R, SUM(PRIM $RPRIM(R,PRIM), BMR(R,PRIM,'ADJPRICE')*IMPORTPR.L(R,PRIM)))+0.001;

DISPLAY RTBL0B;
*DISPLAY RTBL0C;
DISPLAY RTBL0;
DISPLAY RTBL0A;
DISPLAY RTBL21;
*DISPLAY RTBL20;
*DISPLAY RTBL13E;
DISPLAY RTBL13E2;
DISPLAY RTBL6A
DISPLAY RTBL6B
DISPLAY RTBL9;
DISPLAY RTBL9A;
DISPLAY RTBL9C;
DISPLAY RTBL1B2;
DISPLAY RTBL1C2;
*DISPLAY RTBL1D;
DISPLAY RTBL1E;
*DISPLAY RTBL7B;
DISPLAY RTBL7B2;
*DISPLAY RTBL13C;
DISPLAY RTBL13C2;
*DISPLAY RTBL13D;
DISPLAY RTBL13D2;
DISPLAY RTBL16;
DISPLAY RTBL17;
*DISPLAY VALIDATION.M;
OPTION RTBL2:3:1:1; DISPLAY $OC('PRODUCTS') RTBL2;
OPTION RTBL1:3:3:1; DISPLAY $OC('PRODUCTS') RTBL1;
OPTION RTBL6:3:1:1; DISPLAY $OC('PPRICES') RTBL6;
OPTION RTBL5:3:2:1; DISPLAY $OC('PPRICES') RTBL5;
OPTION RTBL8:3:2:1; DISPLAY $OC('INPUTS') RTBL8;
OPTION RTBL7:3:3:1; DISPLAY $OC('INPUTS') RTBL7;
OPTION RTBL12:3:1:1; DISPLAY $OC('IPRICES') RTBL12;
OPTION RTBL11:3:2:1; DISPLAY $OC('IPRICES') RTBL11;
OPTION RTBL14:3:1:1; DISPLAY $OC('PRODACT') RTBL14;
OPTION RTBL13B:3:1:1; DISPLAY $OC('PRODACT') RTBL13B;
OPTION RTBL13:3:2:1; DISPLAY $OC('PRODACT') RTBL13;
*OPTION RTBL17:3:1:1; DISPLAY $OC('CROPAREA') RTBL17;
*OPTION RTBL16:3:2:1; DISPLAY $OC('CROPAREA') RTBL16;
 
* Generate solution tables for dairy
SET DPROD(P)  Diary products
 /MILK, DCALFM, DCALFF, SKIMMILK, MILKFAT, KMILK, CHEESE, BUTTER, CREAM, DRYMILK, DRYMILK2/;
 
  
* Generate variable and constraint tables
 

PARAMETER VTBL1(R,SR,AS,TH2)  Subregional results for production activities;
VTBL1(R,SR,AS,TH2) = 0.0;
VTBL1(R,SR,AS,'LOWER') $RSRAS(R,SR,AS) = PRODSR.LO(R,SR,AS);
VTBL1(R,SR,AS,'LEVEL') $RSRAS(R,SR,AS) = PRODSR.L(R,SR,AS);
VTBL1(R,SR,AS,'UPPER') $RSRAS(R,SR,AS) = PRODSR.UP(R,SR,AS);
VTBL1(R,SR,AS,'MARGINAL') $RSRAS(R,SR,AS) = PRODSR.M(R,SR,AS);
OPTION VTBL1:3:1:1; DISPLAY $OC('VARS') VTBL1;
  
PARAMETER VTBL3(R,CR,TH2)  Regional results for processing activities;
VTBL3(R,CR,TH2) = 0.0;

VTBL3(R,CR,'LOWER') $RCR(R,CR) = PROCR.LO(R,CR);
VTBL3(R,CR,'LEVEL') $RCR(R,CR) = PROCR.L(R,CR);
VTBL3(R,CR,'UPPER') $RCR(R,CR) = PROCR.UP(R,CR);
VTBL3(R,CR,'MARGINAL') $RCR(R,CR) = PROCR.M(R,CR);
OPTION VTBL3:3:2:1; DISPLAY $OC('VARS') VTBL3;
 
PARAMETER VTBL6(R,IR,TH2)  Results for regional input supply activities;
VTBL6(R,IR,TH2) = 0.0;
VTBL6(R,IR,'LOWER') $IRES(R,IR) = SUPPLYIR.LO(R,IR);
VTBL6(R,IR,'LEVEL') $IRES(R,IR) = SUPPLYIR.L(R,IR);
VTBL6(R,IR,'UPPER') $IRES(R,IR) = SUPPLYIR.UP(R,IR);
VTBL6(R,IR,'MARGINAL') $IRES(R,IR) = SUPPLYIR.M(R,IR);
OPTION VTBL6:3:2:1; DISPLAY $OC('VARS') VTBL6;
 
PARAMETER VTBL5(R,SR,IS,TH2)  Results for subregional input supply activities;
VTBL5(R,SR,IS,TH2) = 0.0;
VTBL5(R,SR,IS,'LOWER') $ISES(R,SR,IS) = SUPPLYIS.LO(R,SR,IS);
VTBL5(R,SR,IS,'LEVEL') $ISES(R,SR,IS) = SUPPLYIS.L(R,SR,IS);
VTBL5(R,SR,IS,'UPPER') $ISES(R,SR,IS) = SUPPLYIS.UP(R,SR,IS);
VTBL5(R,SR,IS,'MARGINAL') $ISES(R,SR,IS) = SUPPLYIS.M(R,SR,IS);
OPTION VTBL5:3:3:1; DISPLAY $OC('VARS') VTBL5;
 
PARAMETER VTBL9(R,PR,TH2)  Results for regional product demand activities;

VTBL9(R,PR,TH2) = 0.0;
VTBL9(R,PR,'LOWER') $PRED(R,PR) = DEMANDPR.LO(R,PR);
VTBL9(R,PR,'LEVEL') $PRED(R,PR) = DEMANDPR.L(R,PR);
VTBL9(R,PR,'UPPER') $PRED(R,PR) = DEMANDPR.UP(R,PR);
VTBL9(R,PR,'MARGINAL') $PRED(R,PR) = DEMANDPR.M(R,PR);
OPTION VTBL9:3:2:1; DISPLAY $OC('VARS') VTBL9;
 
PARAMETER VTBL8(R,SR,PS,TH2)  Results for subregional product demand activities;
VTBL8(R,SR,PS,TH2) = 0.0;
VTBL8(R,SR,PS,'LOWER') $PSED(R,SR,PS) = DEMANDPS.LO(R,SR,PS);
VTBL8(R,SR,PS,'LEVEL') $PSED(R,SR,PS) = DEMANDPS.L(R,SR,PS);
VTBL8(R,SR,PS,'UPPER') $PSED(R,SR,PS) = DEMANDPS.UP(R,SR,PS);
VTBL8(R,SR,PS,'MARGINAL') $PSED(R,SR,PS) = DEMANDPS.M(R,SR,PS);
OPTION VTBL8:3:2:1; DISPLAY $OC('VARS') VTBL8;
 
PARAMETER VTBL11(R,PR,TH2)  Results for regional product export activities;
VTBL11(R,PR,TH2) = 0.0;
VTBL11(R,PR,'LOWER') $RPREX(R,PR) = EXPORTRP.LO(R,PR);
VTBL11(R,PR,'LEVEL') $RPREX(R,PR) = EXPORTRP.L(R,PR);
VTBL11(R,PR,'UPPER') $RPREX(R,PR) = EXPORTRP.UP(R,PR);
VTBL11(R,PR,'MARGINAL') $RPREX(R,PR) = EXPORTRP.M(R,PR);
OPTION VTBL11:3:2:1; DISPLAY $OC('VARS') VTBL11;
 
PARAMETER VTBL13(R,PR,TH2)  Results for regional product import activities;
VTBL13(R,PR,TH2) = 0.0;
VTBL13(R,PR,'LOWER') $RPRIM(R,PR) = IMPORTPR.LO(R,PR);
VTBL13(R,PR,'LEVEL') $RPRIM(R,PR) = IMPORTPR.L(R,PR);
VTBL13(R,PR,'UPPER') $RPRIM(R,PR) = IMPORTPR.UP(R,PR);
VTBL13(R,PR,'MARGINAL') $RPRIM(R,PR) = IMPORTPR.M(R,PR);
OPTION VTBL13:3:2:1; DISPLAY $OC('VARS') VTBL13;
 
PARAMETER VTBL15(RS,RD,IP,TH2)  Results for inter-regional transportation activities;
VTBL15(RS,RD,IP,TH2) = 0.0;
VTBL15(RS,RD,IP,'LOWER') $TIP(RS,RD,IP) = TRANIP.LO(RS,RD,IP);
VTBL15(RS,RD,IP,'LEVEL') $TIP(RS,RD,IP) = TRANIP.L(RS,RD,IP);
VTBL15(RS,RD,IP,'UPPER') $TIP(RS,RD,IP) = TRANIP.UP(RS,RD,IP);
VTBL15(RS,RD,IP,'MARGINAL') $TIP(RS,RD,IP) = TRANIP.M(RS,RD,IP);
VTBL15(RS,RD,IP,TH2) $(TRANIP.L(RS,RD,IP) EQ 0) = 0.0;
OPTION VTBL15:3:3:1; DISPLAY $OC('VARS') VTBL15;
 
PARAMETER CTBL2(R,PR,TH2)  Results for regional product balance equations;
CTBL2(R,PR,TH2) = 0.0;
CTBL2(R,PR,'LOWER') $RPR(R,PR) = PRODUCTRE.LO(R,PR) $PRED(R,PR) + PRODUCTRF.LO(R,PR) $PRFD(R,PR);

CTBL2(R,PR,'LEVEL') $RPR(R,PR) = PRODUCTRE.L(R,PR) $PRED(R,PR) + PRODUCTRF.L(R,PR) $PRFD(R,PR);
CTBL2(R,PR,'UPPER') $RPR(R,PR) = PRODUCTRE.UP(R,PR) $PRED(R,PR) + PRODUCTRF.UP(R,PR) $PRFD(R,PR);
CTBL2(R,PR,'MARGINAL') $RPR(R,PR) = PRODUCTRE.M(R,PR) $PRED(R,PR) + PRODUCTRF.M(R,PR) $PRFD(R,PR);
OPTION CTBL2:3:2:1; DISPLAY $OC('EQNS') CTBL2;
 
PARAMETER CTBL1(R,SR,PS,TH2)  Results for subregional product balance equations;
CTBL1(R,SR,PS,TH2) = 0.0;
CTBL1(R,SR,PS,'LOWER') $RSRPS(R,SR,PS) = PRODUCTSE.LO(R,SR,PS) $PSED(R,SR,PS)
                                       + PRODUCTSF.LO(R,SR,PS) $PSFD(R,SR,PS);
CTBL1(R,SR,PS,'LEVEL') $RSRPS(R,SR,PS) = PRODUCTSE.L(R,SR,PS) $PSED(R,SR,PS)
                                       + PRODUCTSF.L(R,SR,PS) $PSFD(R,SR,PS);
CTBL1(R,SR,PS,'UPPER') $RSRPS(R,SR,PS) = PRODUCTSE.UP(R,SR,PS) $PSED(R,SR,PS)
                                       + PRODUCTSF.UP(R,SR,PS) $PSFD(R,SR,PS);
CTBL1(R,SR,PS,'MARGINAL') $RSRPS(R,SR,PS) = PRODUCTSE.M(R,SR,PS) $PSED(R,SR,PS)
                                          + PRODUCTSF.M(R,SR,PS) $PSFD(R,SR,PS);
OPTION CTBL1:3:3:1; DISPLAY $OC('EQNS') CTBL1;
 
PARAMETER CTBL5(R,IR,TH2)  Results for regional input balance equations;
CTBL5(R,IR,TH2) = 0.0;

CTBL5(R,IR,'LOWER') $RIR(R,IR) = INPUTRE.LO(R,IR) $IRES(R,IR) + INPUTRF.LO(R,IR) $IRFS(R,IR);
CTBL5(R,IR,'LEVEL') $RIR(R,IR) = INPUTRE.L(R,IR) $IRES(R,IR) + INPUTRF.L(R,IR) $IRFS(R,IR);
CTBL5(R,IR,'UPPER') $RIR(R,IR) = INPUTRE.UP(R,IR) $IRES(R,IR) + INPUTRF.UP(R,IR) $IRFS(R,IR);
CTBL5(R,IR,'MARGINAL') $RIR(R,IR) = INPUTRE.M(R,IR) $IRES(R,IR) + INPUTRF.M(R,IR) $IRFS(R,IR);

OPTION CTBL5:3:2:1; DISPLAY $OC('EQNS') CTBL5;

PARAMETER CTBL4(R,SR,IS,TH2)  Results for subregional input balance equations;
CTBL4(R,SR,IS,TH2) = 0.0;
CTBL4(R,SR,IS,'LOWER') $RSRIS(R,SR,IS) = INPUTSE.LO(R,SR,IS) $ISES(R,SR,IS)
                                       + INPUTSF.LO(R,SR,IS) $ISFS(R,SR,IS);
CTBL4(R,SR,IS,'LEVEL') $RSRIS(R,SR,IS) = INPUTSE.L(R,SR,IS) $ISES(R,SR,IS)
                                       + INPUTSF.L(R,SR,IS) $ISFS(R,SR,IS);
CTBL4(R,SR,IS,'UPPER') $RSRIS(R,SR,IS) = INPUTSE.UP(R,SR,IS) $ISES(R,SR,IS)
                                       + INPUTSF.UP(R,SR,IS) $ISFS(R,SR,IS);
CTBL4(R,SR,IS,'MARGINAL') $RSRIS(R,SR,IS) = INPUTSE.M(R,SR,IS) $ISES(R,SR,IS)
                                          + INPUTSF.M(R,SR,IS) $ISFS(R,SR,IS);
OPTION CTBL4:3:3:1; DISPLAY $OC('EQNS') CTBL4;
 

Set dummy /Units/;
* ett dummy-index för att göra en kolumn

Parameter RTBL15_exp(AS,dummy);

* Fyll hjälpparametern
RTBL15_exp(AS,'Units') = RTBL15(AS);


$set outputPathAndFileName %resultFolder%\%scenarioName%
execute_unload "%outputPathAndFileName%.gdx" RTBL4, RTBL10, RTBL15_exp, RTBL13E2, RTBL1B2, RTBL1C2, EAS;

execute "gdxxrw i=%outputPathAndFileName%.gdx o=%outputPathAndFileName%.xlsx par=RTBL4 rng=Products!A1 par=RTBL10 rng=Inputs!A1 par=RTBL15_exp rng=Activities!A1 par=RTBL13E2 rng=Regions!A1";
execute "gdxxrw i=%outputPathAndFileName%.gdx o=%outputPathAndFileName%.xlsx par=RTBL1B2 rng=Regions!A35 par=RTBL1C2 rng=Regions!A60";
execute "gdxxrw i=%outputPathAndFileName%.gdx o=%outputPathAndFileName%.xlsx par=EAS rng=EAS!A1 squeeze=no";
