*Add-on module used in calculations with trade restrictions

RED = (1-0.50);
 
*EAS(R,SR,ECO,'ACRECO')$RSRAS(R,SR,ECO) = 0;
EAS(R,SR,'EDCOW1','MEDCOW')$RSRAS(R,SR,'EDCOW1') = 0;
EAS(R,SR,'EDCOW2','MEDCOW')$RSRAS(R,SR,'EDCOW2') = 0;
EAS(R,SR,'EDCOW3','MEDCOW')$RSRAS(R,SR,'EDCOW3') = 0;
EAS(R,SR,'EBEEFCATT','MEBEEFCATT')$RSRAS(R,SR,'EBEEFCATT') = 0;
EAS(R,SR,'EBEEFCAT2','MEBEEFCATT')$RSRAS(R,SR,'EBEEFCAT2') = 0;
EAS(R,SR,'ECOPIG','MECOPIG')$RSRAS(R,SR,'ECOPIG') = 0;
EAS(R,SR,'ESHEEP','MESHEEP')$RSRAS(R,SR,'ESHEEP') = 0;
EAS(R,SR,'EPOULTRY','MEPOULTRY')$RSRAS(R,SR,'EPOULTRY') = 0;

EAS(R,SR,CROPS3,'POWER')$RSRAS(R,SR,CROPS3) = EAS(R,SR,CROPS3,'POWER')* (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,'DIESEL')$RSRAS(R,SR,CROPS3) = EAS(R,SR,CROPS3,'DIESEL')* (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,'LABOR')$RSRAS(R,SR,CROPS3) = EAS(R,SR,CROPS3,'LABOR')* (1-(1-RED)*0.4);
EAS(R,SR,CROPS3,'NITROGEN')$RSRAS(R,SR,CROPS3) = EAS(R,SR,CROPS3,'NITROGEN')* (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,'PHOSPHORUS')$RSRAS(R,SR,CROPS3) = EAS(R,SR,CROPS3,'PHOSPHORUS')* (1-(1-RED)*0.8);
EAS(R,SR,CROPS3,'POTASSIUM')$RSRAS(R,SR,CROPS3) = EAS(R,SR,CROPS3,'POTASSIUM')* (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,'PESTICIDES')$RSRAS(R,SR,CROPS3) = EAS(R,SR,CROPS3,'PESTICIDES')* (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,'HERBICIDES')$RSRAS(R,SR,CROPS3) = EAS(R,SR,CROPS3,'HERBICIDES')* (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,'FUNGICIDES')$RSRAS(R,SR,CROPS3) = EAS(R,SR,CROPS3,'FUNGICIDES')* (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,'INSECTICID')$RSRAS(R,SR,CROPS3) = EAS(R,SR,CROPS3,'INSECTICID')* (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,'GLYFOSAT')$RSRAS(R,SR,CROPS3)   = EAS(R,SR,CROPS3,'GLYFOSAT')  * (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,'PLASTIC')$RSRAS(R,SR,CROPS3)    = EAS(R,SR,CROPS3,'PLASTIC')   * (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,'OILGRSEED')$RSRAS(R,SR,CROPS3)  = EAS(R,SR,CROPS3,'OILGRSEED') * (1-(1-RED)*0.5);
EAS(R,SR,CROPS3,PR)$RSRAS(R,SR,CROPS3)      = EAS(R,SR,CROPS3,PR)     * (1-(1-RED)*0.2);

EAS(R,SR,ECROPS3,'POWER')$RSRAS(R,SR,ECROPS3) = EAS(R,SR,ECROPS3,'POWER')* (1-(1-RED)*0.5);
EAS(R,SR,ECROPS3,'DIESEL')$RSRAS(R,SR,ECROPS3) = EAS(R,SR,ECROPS3,'DIESEL')* (1-(1-RED)*0.5);
EAS(R,SR,ECROPS3,'LABOR')$RSRAS(R,SR,ECROPS3) = EAS(R,SR,ECROPS3,'LABOR')* (1-(1-RED)*0.4);
EAS(R,SR,ECROPS3,PR)$RSRAS(R,SR,ECROPS3)      = EAS(R,SR,ECROPS3,PR)     * (1-(1-RED)*0.2);
EAS(R,SR,ECROPS3,'ECON')$RSRAS(R,SR,ECROPS3) = EAS(R,SR,ECROPS3,'ECON')* (1-(1-RED)*0.25);
EAS(R,SR,ECROPS3,'ECOP')$RSRAS(R,SR,ECROPS3) = EAS(R,SR,ECROPS3,'ECOP')* (1-(1-RED)*0.40);
EAS(R,SR,ECROPS3,'ECOK')$RSRAS(R,SR,ECROPS3) = EAS(R,SR,ECROPS3,'ECOK')* (1-(1-RED)*0.25);
EAS(R,SR,ECROPS3,PR)$RSRAS(R,SR,ECROPS3) = EAS(R,SR,ECROPS3,PR)* (1-(1-RED)*0.1);

*EAS(R,SR,AS,'NITROGEN')$RSRAS(R,SR,AS)   = EAS(R,SR,AS,'NITROGEN')   + EAS(R,SR,AS,'ECON');
*EAS(R,SR,AS,'PHOSPHORUS')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'PHOSPHORUS') + EAS(R,SR,AS,'ECOP');
*EAS(R,SR,AS,'POTASSIUM')$RSRAS(R,SR,AS)  = EAS(R,SR,AS,'POTASSIUM')  + EAS(R,SR,AS,'ECOK');

*EAS(R,SR,AS,'ECON') = 0;
*EAS(R,SR,AS,'ECOP') = 0;
*EAS(R,SR,AS,'ECOK') = 0;
*EAS(R,SR,AS,ECOPROD) = 0;
*EAS(R,SR,AS,'ACRECO') = 0;

*EAS(R,SR,AS,'MAXWHEAT')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'MAXWHEAT') + EAS(R,SR,AS,'MAXEWHEAT');
*EAS(R,SR,AS,'MAXEWHEAT')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'MAXWWHEAT')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'MAXWWHEAT') + EAS(R,SR,AS,'MAXEWWHEAT');
*EAS(R,SR,AS,'MAXEWWHEAT')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'MAXWRAY')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'MAXWRAY') + EAS(R,SR,AS,'MAXEWRAY');
*EAS(R,SR,AS,'MAXEWRAY')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'MAXOILG')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'MAXOILG') + EAS(R,SR,AS,'MAXEOILG');
*EAS(R,SR,AS,'MAXEOILG')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'MAXWOILG')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'MAXWOILG') + EAS(R,SR,AS,'MAXEWOILG');
*EAS(R,SR,AS,'MAXEWOILG')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'MAXPEAS')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'MAXPEAS') + EAS(R,SR,AS,'MAXEPEAS');
*EAS(R,SR,AS,'MAXEPEAS')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'MAXPOTATO')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'MAXPOTATO') + EAS(R,SR,AS,'MAXEPOTATO');
*EAS(R,SR,AS,'MAXEPOTATO')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'MAXSUGAR')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'MAXSUGAR') + EAS(R,SR,AS,'MAXESUGAR');
*EAS(R,SR,AS,'MAXESUGAR')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'MINNEWFOR')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'MINNEWFOR') + EAS(R,SR,AS,'MINENEWFOR');
*EAS(R,SR,AS,'MINENEWFOR')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'MAXLATE')$RSRAS(R,SR,AS) = EAS(R,SR,AS,'MAXLATE') + EAS(R,SR,AS,'MAXELATE');
*EAS(R,SR,AS,'MAXELATE')$RSRAS(R,SR,AS) = 0;

*EAS(R,SR,AS,'ORGCROPL')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'ORGPASTR')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'CBONDING')$RSRAS(R,SR,AS) = 0;
*EAS(R,SR,AS,'NH3')$RSRAS(R,SR,AS)      = 0;
*EAS(R,SR,AS,'CO2')$RSRAS(R,SR,AS)      = 0;
*EAS(R,SR,AS,'CH4')$RSRAS(R,SR,AS)      = 0;
*EAS(R,SR,AS,'N2O')$RSRAS(R,SR,AS)      = 0;
*EAS(R,SR,AS,'CO2EQ')$RSRAS(R,SR,AS)    = 0;
*EAS(R,SR,AS,'N-LEAKAGE')$RSRAS(R,SR,AS)= 0;
*EAS(R,SR,AS,'P-LEAKAGE')$RSRAS(R,SR,AS)= 0;

*SUPPLYIS.UP(R,SR,'N-LEAKAGE')= 0;
*SUPPLYIS.UP(R,SR,'P-LEAKAGE')= 0;

SUPPLYIN.UP('DIESEL')    = SUPPLYIN.L('DIESEL')    * RED * 1.00001;
SUPPLYIN.UP('HERBICIDES')= SUPPLYIN.L('HERBICIDES')* RED * 1.00001;
SUPPLYIN.UP('GLYFOSAT')  = SUPPLYIN.L('GLYFOSAT')  * RED * 1.00001;
SUPPLYIN.UP('FUNGICIDES')= SUPPLYIN.L('FUNGICIDES')* RED * 1.00001;
SUPPLYIN.UP('INSECTICID')= SUPPLYIN.L('INSECTICID')* RED * 1.00001;
*SUPPLYIN.UP('OTHERFEED') = SUPPLYIN.L('OTHERFEED') * RED * 1.00001;
SUPPLYIN.UP('PLASTIC')   = SUPPLYIN.L('PLASTIC')   * (1-(1-RED)*0.5) * 1.00001;

SUPPLYIR.UP(R,'NITROGEN')  = SUPPLYIR.L(R,'NITROGEN')   * RED * 1.00001;
SUPPLYIR.UP(R,'PHOSPHORUS')= SUPPLYIR.L(R,'PHOSPHORUS') * RED * 1.00001;
SUPPLYIR.UP(R,'POTASSIUM') = SUPPLYIR.L(R,'POTASSIUM')  * RED * 1.00001;

SUPPLYIR.UP(R,'SOJA')      = SUPPLYIR.L(R,'SOJA')       * RED * 1.00001;
SUPPLYIR.UP(R,'BETFOR')    = SUPPLYIR.L(R,'BETFOR')     * RED * 1.00001;
SUPPLYIR.UP(R,'PROTFEED')  = SUPPLYIR.L(R,'PROTFEED')   * RED * 1.00001;
SUPPLYIR.UP(R,'OILGRSEED') = SUPPLYIR.L(R,'OILGRSEED')  * RED * 1.00001;
SUPPLYIR.UP(R,'POTATOSEED')= SUPPLYIR.L(R,'POTATOSEED') * RED * 1.00001;
SUPPLYIR.UP(R,'SUGARBSEED')= SUPPLYIR.L(R,'SUGARBSEED') * RED * 1.00001;

SUPPLYIS.UP(R,SR,'ECON')   = SUPPLYIS.L(R,SR,'ECON')    * RED * 1.00001;
SUPPLYIS.UP(R,SR,'ECOP')   = SUPPLYIS.L(R,SR,'ECOP')    * RED * 1.00001;
SUPPLYIS.UP(R,SR,'ECOK')   = SUPPLYIS.L(R,SR,'ECOK')    * RED * 1.00001;
SUPPLYIS.UP(R,SR,'ACRECON')= SUPPLYIS.L(R,SR,'ACRECON');

BIR(R,'MAXFISH','MAX')  = BIR(R,'MAXFISH','MAX')  * (1-(1-RED)*0.1);
BIR(R,'MAXFRUIT','MAX') = BIR(R,'MAXFRUIT','MAX') * (1-(1-RED)*0.2);
BIR(R,'MAXVEGET','MAX') = BIR(R,'MAXVEGET','MAX') * (1-(1-RED)*0.75);

IMPORTPR.UP(R,PR) $RPRIM(R,PR) = IMPORTPR.L(R,PR) * RED; 
EXPORTRP.UP(R,PR) $RPREX(R,PR) = EXPORTRP.L(R,PR) * RED; 
IMPORTPR.UP(R,'COARSGRAIN') $RPRIM(R,'COARSGRAIN') = 0;

*PRODSR.FX(R,SR,'USEMANURE')= 0;
*$offtext
* No pigs, poultry or cattle.
*PRODSR.UP(R,SR,'SOW1')= 0;
*PRODSR.UP(R,SR,'ECOPIG')= 0;

*PRODSR.UP(R,SR,'POULTRY')= 0;
*PRODSR.LO(R,SR,'POULTRY')= 0;
*PRODSR.UP(R,SR,'CHICKEN')= 0;
*PRODSR.UP(R,SR,'EPOULTRY')= 0;
*IMPORTPR.UP(R,'EGG') $RPRIM(R,'EGG') = 1000;
*EXPORTRP.UP(R,'EGG') $RPREX(R,'EGG') = 0;
*BMR(R,'EGG','ADJPRICE') $RPRIM(R,'EGG') = 16.075;
*IMPORTPR.UP(R,'PLTRYMEAT') $RPRIM(R,'PLTRYMEAT') = 1000;
*EXPORTRP.UP(R,'PLTRYMEAT') $RPREX(R,'PLTRYMEAT') = 0;
*BMR(R,'PLTRYMEAT','ADJPRICE') $RPRIM(R,'PLTRYMEAT') = 34;

*PRODSR.UP(R,SR,DCOWS)= 0;
*PRODSR.UP(R,SR,BCOWS)= 0;

*DEMANDPR.LO(R,'PROTEINA')$PRED(R,'PROTEINA')      = 0;

SOLVE SASM USING NLP MAXIMIZING Z;

*$ontext
*EAS(R,SR,DCOWS,'DPTRANR')$RSRAS(R,SR,DCOWS) =  EAS(R,SR,DCOWS,'DPTRANR') * 1.28;
EAS(R,SR,DCOWS,'DPTRANR')$RSRAS(R,SR,DCOWS) =  EAS(R,SR,DCOWS,'DPTRANR') *
    (1-(1-SUPPLYIN.L('DPTRANC')/DEMANDPN.L('DPTRANR'))*0.90);

SOLVE SASM USING NLP MAXIMIZING Z;

EAS(R,SR,DCOWS,'DPTRANR')$RSRAS(R,SR,DCOWS) =  EAS(R,SR,DCOWS,'DPTRANR') *
    (1-(1-SUPPLYIN.L('DPTRANC')/DEMANDPN.L('DPTRANR'))*0.90);

SOLVE SASM USING NLP MAXIMIZING Z;

EAS(R,SR,DCOWS,'DPTRANR')$RSRAS(R,SR,DCOWS) =  EAS(R,SR,DCOWS,'DPTRANR') *
    (1-(1-SUPPLYIN.L('DPTRANC')/DEMANDPN.L('DPTRANR'))*0.90);

SOLVE SASM USING NLP MAXIMIZING Z;

EAS(R,SR,DCOWS,'DPTRANR')$RSRAS(R,SR,DCOWS) =  EAS(R,SR,DCOWS,'DPTRANR') *
    (1-(1-SUPPLYIN.L('DPTRANC')/DEMANDPN.L('DPTRANR'))*0.90);
    
SOLVE SASM USING NLP MAXIMIZING Z;

EAS(R,SR,DCOWS,'DPTRANR')$RSRAS(R,SR,DCOWS) =  EAS(R,SR,DCOWS,'DPTRANR') *
    (1-(1-SUPPLYIN.L('DPTRANC')/DEMANDPN.L('DPTRANR'))*0.90);
    
SOLVE SASM USING NLP MAXIMIZING Z;
* halv import utan lager
